## Ответы на вопросы

### i. Выведите аналитическое решение проблемы регрессии. Используйте векторную форму уравнения

**Аналитическое решение задачи линейной регрессии:**

Для модели $\hat{y} = X\theta + b$ (где $X \in \mathbb{R}^{n \times d}$, $y \in \mathbb{R}^n$)

Расширим матрицу признаков столбцом единиц: $\tilde{X} = [1, X]$

Функция потерь: $L(\theta) = \frac{1}{n}\|y - \tilde{X}\theta\|^2$

Приравнивая градиент к нулю: $\nabla L(\theta) = 0$

Получаем: $\tilde{X}^T\tilde{X}\theta = \tilde{X}^Ty$

**Финальное решение:**
$$\theta^* = (\tilde{X}^T\tilde{X})^{-1}\tilde{X}^Ty$$

где $\theta^* = [b^*, w_1^*, w_2^*, \ldots, w_d^*]^T$ - оптимальные параметры модели.

### ii. Что изменяется в решении при добавлении L1 и L2 регуляризации в функцию потерь.

**L2-регуляризация (Ridge):**
- Функция потерь: $L(\theta) = \frac{1}{n}\|y - \tilde{X}\theta\|^2 + \lambda\|\theta\|_2^2$
- **Изменение решения**: $\theta^*_{L2} = (\tilde{X}^T\tilde{X} + n\lambda I)^{-1}\tilde{X}^Ty$
- **Ключевые изменения**:
  - Добавляется $\lambda I$ к матрице $\tilde{X}^T\tilde{X}$
  - Решение всегда существует (даже при вырожденной матрице)
  - Все веса сжимаются к нулю, но не обнуляются

**L1-регуляризация (Lasso):**
- Функция потерь: $L(\theta) = \frac{1}{n}\|y - \tilde{X}\theta\|^2 + \lambda\|\theta\|_1$
- **Изменение решения**: Нет замкнутой аналитической формы
- **Ключевые изменения**:
  - Некоторые веса точно обнуляются (разреженность)
  - Выполняется автоматический отбор признаков
  - Решение находится итеративными методами
  - Может быть не единственным

**Основное отличие**: L2 сжимает веса, L1 обнуляет неважные признаки.

### iii. Объясните, почему L1-регуляризация часто используется для выбора признаков. Почему существует много весов, равных 0 после того, как модель подходит?

**Геометрическая причина обнуления весов:**

L1-норма $\|\theta\|_1 = \sum_{j=1}^d |\theta_j|$ образует **ромб** в пространстве параметров с **углами на осях координат**. Минимум функции потерь часто достигается именно в этих углах, где некоторые координаты равны нулю.

**Математическое объяснение:**

Для функции потерь $L(\theta) = \|y - \tilde{X}\theta\|^2 + \lambda\|\theta\|_1$ условие оптимальности:
$$\frac{\partial L}{\partial \theta_j} = -2\tilde{X}_j^T(y - \tilde{X}\theta) + \lambda \cdot \text{sign}(\theta_j) = 0$$

Если $|2\tilde{X}_j^T(y - \tilde{X}\theta)| < \lambda$, то оптимальное решение $\theta_j^* = 0$.

**Интуитивное объяснение:**

L1-регуляризация "штрафует" каждый ненулевой вес одинаково. Если признак не дает достаточного улучшения предсказания (меньше порога $\lambda$), "дешевле" обнулить его вес, чем платить штраф.

**Почему L1 используется для выбора признаков:**

1. **Автоматический отбор**: Обнуляет неважные признаки
2. **Разреженность**: Создает модели с малым числом ненулевых весов  
3. **Интерпретируемость**: Легко понять, какие признаки важны
4. **Сокращение размерности**: Уменьшает количество признаков в модели

**Сравнение с L2:**
- L2 образует сферу (гладкая поверхность) → не обнуляет веса
- L1 образует ромб (углы на осях) → обнуляет веса в углах

### iv. Объясните, как вы можете использовать одни и те же модели (линейная регрессия, хребет и т.д.), но дайте возможность соответствовать нелинейным зависимостям

**Основная идея: Расширение признакового пространства**

Линейные модели остаются линейными по параметрам θ, но становятся нелинейными по входным данным x через преобразование признаков:

$$\hat{y} = \theta^T\phi(x) + b$$

где $\phi(x)$ - нелинейное преобразование признаков.

**Основные методы преобразования признаков:**

1. **Полиномиальные признаки**: $\phi(x) = [1, x, x^2, x^3, \ldots, x^d]$
   - Для многомерного случая: все комбинации степеней до d
   - Пример: $[1, x_1, x_2, x_1^2, x_1x_2, x_2^2]$ для степени 2

2. **Радиальные базисные функции (RBF)**: 
   $$\phi_i(x) = \exp\left(-\frac{\|x - \mu_i\|^2}{2\sigma^2}\right)$$

3. **Тригонометрические функции**: $\phi(x) = [1, \sin(x), \cos(x), \sin(2x), \cos(2x)]$

4. **Логарифмические/экспоненциальные**: $\phi(x) = [1, x, \log(x), e^x]$

5. **Взаимодействия признаков**: $\phi(x_1, x_2) = [1, x_1, x_2, x_1x_2]$

**Преимущества:**
- Используем те же алгоритмы (Linear, Ridge, Lasso)
- Сохраняем интерпретируемость
- Можем применить любую регуляризацию

**Недостатки:**
- Проклятие размерности (экспоненциальный рост признаков)
- Риск переобучения
- Необходимость выбора подходящих преобразований

**Практические рекомендации:**
- Начинайте с малых степеней полиномов (d=2,3)
- Используйте регуляризацию для борьбы с переобучением
- Применяйте нормализацию признаков

## 2. Введение - выполняем предпроцессинг

### 2.1. Импорт библиотек

Импортируем все необходимые библиотеки для работы с данными, машинным обучением и визуализацией.

In [1]:
# Импорт библиотек
# Основные библиотеки для работы с данными
import pandas as pd
import numpy as np
import json

# Библиотеки для машинного обучения
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.preprocessing import MinMaxScaler, StandardScaler, PolynomialFeatures
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import scipy
import statsmodels.api as sm

# Библиотеки для визуализации
import matplotlib.pyplot as plt
import seaborn as sns

# Библиотеки для работы с коллекциями
from collections import Counter

# Дополнительные утилиты
import warnings
warnings.filterwarnings('ignore')

# Настройка для воспроизводимости результатов
np.random.seed(21)

print("✅ Все библиотеки успешно импортированы")

✅ Все библиотеки успешно импортированы

In [2]:
# ============================================================================
# НАСТРОЙКИ ДЛЯ УСКОРЕНИЯ ПОВТОРНЫХ ЗАПУСКОВ
# ============================================================================

# Флаг для пропуска долгих экспериментов с alpha (пункт 8.6)
SKIP_ALPHA_EXPERIMENTS = True  # Измените на False, если хотите запустить

print(f"⚙️ НАСТРОЙКИ:")
print(f"   SKIP_ALPHA_EXPERIMENTS = {SKIP_ALPHA_EXPERIMENTS}")

⚙️ НАСТРОЙКИ:
   SKIP_ALPHA_EXPERIMENTS = True

### 2.2. Чтение обучающей и тестовой выборок

Загружаем данные из JSON файлов.

In [3]:
# Чтение данных из JSON файлов
train_df = pd.read_json('../data/train.json')
test_df = pd.read_json('../data/test.json')

print(f"Размер обучающей выборки: {train_df.shape}")
print(f"Размер тестовой выборки: {test_df.shape}")
print("\n✅ Данные успешно загружены")

Размер обучающей выборки: (49352, 15)
Размер тестовой выборки: (74659, 14)

✅ Данные успешно загружены

### 2.3. Препроцессинг признака Interest Level

Кодируем категориальную переменную `interest_level` в числовые значения.

In [4]:
# Препроцессинг interest_level
interest_level_map = {'low': 0, 'medium': 1, 'high': 2}
train_df['interest_level'] = train_df['interest_level'].map(interest_level_map)

print("Распределение interest_level:")
print(train_df['interest_level'].value_counts().sort_index())
print("\n✅ Interest_level закодирован")

Распределение interest_level:
interest_level
0    34284
1    11229
2     3839
Name: count, dtype: int64

✅ Interest_level закодирован

## 3. Вводная часть анализа данных - часть 2

### 3.1. Работа с признаком "Features"

Рассмотрим колонку `features`. Она содержит список удобств для каждой квартиры. Мы создадим новые бинарные признаки на основе самых популярных удобств, что улучшит качество модели.

In [5]:
# Рассмотрим колонку 'features'
print("Примеры данных (первые 5 записей):")
for idx, features in enumerate(train_df['features'].head(5), 1):
    print(f"{idx}. {features}")

Примеры данных (первые 5 записей):
1. ['Dining Room', 'Pre-War', 'Laundry in Building', 'Dishwasher', 'Hardwood Floors', 'Dogs Allowed', 'Cats Allowed']
2. ['Doorman', 'Elevator', 'Laundry in Building', 'Dishwasher', 'Hardwood Floors', 'No Fee']
3. ['Doorman', 'Elevator', 'Laundry in Building', 'Laundry in Unit', 'Dishwasher', 'Hardwood Floors']
4. []
5. ['Doorman', 'Elevator', 'Fitness Center', 'Laundry in Building']

### 3.2. Очистка ненужных символов

Удаляем символы `[`, `]`, `'`, `"` и пробелы из колонки 'features'.

In [6]:
# Очистка ненужных символов
def clean_features(features_list):
    if not isinstance(features_list, list):
        return []
    return [feature.replace(' ', '').replace('-', '').replace('_', '') 
            for feature in features_list if isinstance(feature, str)]

train_df['features_cleaned'] = train_df['features'].apply(clean_features)
test_df['features_cleaned'] = test_df['features'].apply(clean_features)

### 3.3. Сбор всех значений в один список

Получаем все значения из каждого списка колонки 'features_cleaned' и собираем результат в один огромный список для всего датасета. Используем `DataFrame.iterrows()`.

In [7]:
# Сбор всех значений в один список
all_features_cleaned = []

for idx, row in train_df.iterrows():
    if isinstance(row['features_cleaned'], list):
        all_features_cleaned.extend(row['features_cleaned'])

print(f"Общее количество упоминаний: {len(all_features_cleaned)}")

Общее количество упоминаний: 267906

### 3.4. Подсчет уникальных значений

Определяем, сколько уникальных удобств содержится в результирующем списке.

In [8]:
# Подсчет уникальных значений
unique_features = set(all_features_cleaned)

print(f"Количество уникальных удобств: {len(unique_features)}")

Количество уникальных удобств: 1513

### 3.5. Знакомство с библиотекой Collections

Используем библиотеку Collections для эффективного получения количественной статистики о данных. Класс `Counter` позволяет легко подсчитать частоту встречаемости элементов.

In [9]:
# Использование библиотеки Collections
from collections import Counter

features_counter = Counter(all_features_cleaned)

print(f"Всего уникальных удобств: {len(features_counter)}")
print(f"Общее количество упоминаний: {sum(features_counter.values())}")

Всего уникальных удобств: 1513
Общее количество упоминаний: 267906

### 3.6. Определение топ-20 самых популярных удобств

Подсчитываем самые популярные удобства из нашего огромного списка и берём топ-20.

In [10]:
# Топ-20 самых популярных удобств
top_20_features = features_counter.most_common(20)

print("Топ-20 самых популярных удобств:")
for idx, (feature, count) in enumerate(top_20_features, 1):
    print(f"{idx:2d}. {feature:25s} - {count:5d} упоминаний")

top_20_feature_names = [feature for feature, count in top_20_features]

Топ-20 самых популярных удобств:
 1. Elevator                  - 25915 упоминаний
 2. CatsAllowed               - 23540 упоминаний
 3. HardwoodFloors            - 23527 упоминаний
 4. DogsAllowed               - 22035 упоминаний
 5. Doorman                   - 20898 упоминаний
 6. Dishwasher                - 20426 упоминаний
 7. NoFee                     - 18062 упоминаний
 8. LaundryinBuilding         - 16344 упоминаний
 9. FitnessCenter             - 13252 упоминаний
10. PreWar                    -  9151 упоминаний
11. LaundryinUnit             -  8738 упоминаний
12. RoofDeck                  -  6542 упоминаний
13. OutdoorSpace              -  5268 упоминаний
14. DiningRoom                -  5136 упоминаний
15. HighSpeedInternet         -  4299 упоминаний
16. Balcony                   -  2992 упоминаний
17. SwimmingPool              -  2730 упоминаний
18. LaundryInBuilding         -  2593 упоминаний
19. NewConstruction           -  2559 упоминаний
20. Terrace                   -  2283 упоминаний

### 3.7. Проверка соответствия ожидаемым значениям

Согласно заданию, должны получиться следующие удобства: 'Elevator', 'CatsAllowed', 'HardwoodFloors', 'DogsAllowed', 'Doorman', 'Dishwasher', 'NoFee', 'LaundryinBuilding', 'FitnessCenter', 'Pre-War', 'LaundryinUnit', 'RoofDeck', 'OutdoorSpace', 'DiningRoom', 'HighSpeedInternet', 'Balcony', 'SwimmingPool', 'LaundryInBuilding', 'NewConstruction', 'Terrace'.

In [11]:
# Проверка соответствия
expected_features = ['Elevator', 'CatsAllowed', 'HardwoodFloors', 'DogsAllowed', 'Doorman',
                     'Dishwasher', 'NoFee', 'LaundryinBuilding', 'FitnessCenter', 'PreWar',
                     'LaundryinUnit', 'RoofDeck', 'OutdoorSpace', 'DiningRoom',
                     'HighSpeedInternet', 'Balcony', 'SwimmingPool', 'LaundryInBuilding',
                     'NewConstruction', 'Terrace']

matches = len([f for f in top_20_feature_names if f in expected_features])
print(f"Совпадений: {matches}/{len(expected_features)}")

Совпадений: 20/20

### 3.8. Создание бинарных признаков

Создаем 20 новых признаков на основе топ-20 удобств: значение 1, если удобство присутствует в списке "features", иначе 0.

In [12]:
# Создание бинарных признаков
def create_feature_columns(df, feature_names):
    """Создает бинарные колонки для каждого признака из списка."""
    for feature_name in feature_names:
        df[feature_name] = df['features_cleaned'].apply(
            lambda x: 1 if isinstance(x, list) and feature_name in x else 0
        )
    return df

train_df = create_feature_columns(train_df, top_20_feature_names)
test_df = create_feature_columns(test_df, top_20_feature_names)

print("Создано 20 бинарных признаков")

Создано 20 бинарных признаков

### 3.9. Формирование итогового списка признаков

Добавляем 'bathrooms' и 'bedrooms' к топ-20 признакам и создаём специальную переменную `feature_list` со всеми именами признаков. Теперь у нас 22 признака для обучения моделей.

In [13]:
# Формирование итогового списка признаков
feature_list = ['bathrooms', 'bedrooms'] + top_20_feature_names

print(f"Итоговый список сформирован из {len(feature_list)} признаков")
print("\n✅ Подготовка данных завершена!")

Итоговый список сформирован из 22 признаков

✅ Подготовка данных завершена!

## 4. Реализация моделей — Линейная регрессия

В этом разделе мы реализуем линейную регрессию с использованием стохастического градиентного спуска (SGD) и сравним результаты с реализацией sklearn.

### 4.1. Инициализация генератора случайных чисел

Устанавливаем seed = 21 для воспроизводимости результатов.

In [14]:
# Инициализация генератора случайных чисел с seed = 21
np.random.seed(21)

print("✅ Генератор случайных чисел инициализирован с seed = 21")

✅ Генератор случайных чисел инициализирован с seed = 21

### 4.2. Реализация класса Linear Regression с SGD

Реализуем Python класс для линейной регрессии с двумя основными методами — `fit` и `predict`. Используем стохастический градиентный спуск (SGD) для нахождения оптимальных весов модели.

In [15]:
class LinearRegressionSGD:
    """
    Линейная регрессия с использованием стохастического градиентного спуска (SGD).
    """
    
    def __init__(self, learning_rate=0.01, n_iterations=1000, random_state=21):
        """
        Параметры:
        ----------
        learning_rate : float, по умолчанию 0.01
            Скорость обучения (шаг градиентного спуска)
        n_iterations : int, по умолчанию 1000
            Количество итераций обучения
        random_state : int, по умолчанию 21
            Seed для генератора случайных чисел
        """
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.random_state = random_state
        self.weights = None
        self.bias = None
        
    def fit(self, X, y):
        """
        Обучение модели на данных X и целевых значениях y.
        
        Параметры:
        ----------
        X : array-like, shape (n_samples, n_features)
            Обучающие данные
        y : array-like, shape (n_samples,)
            Целевые значения
        """
        # Устанавливаем seed
        np.random.seed(self.random_state)
        
        # Инициализация параметров
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0
        
        # Стохастический градиентный спуск
        for iteration in range(self.n_iterations):
            # Перемешиваем индексы для стохастичности
            indices = np.random.permutation(n_samples)
            
            for idx in indices:
                # Берём один случайный образец
                xi = X[idx:idx+1]
                yi = y[idx:idx+1]
                
                # Предсказание
                y_pred = np.dot(xi, self.weights) + self.bias
                
                # Вычисление градиентов
                dw = -2 * xi.T.dot(yi - y_pred) / 1  # для одного образца
                db = -2 * np.sum(yi - y_pred) / 1
                
                # Обновление весов
                self.weights -= self.learning_rate * dw.flatten()
                self.bias -= self.learning_rate * db
        
        return self
    
    def predict(self, X):
        """
        Предсказание на данных X.
        
        Параметры:
        ----------
        X : array-like, shape (n_samples, n_features)
            Данные для предсказания
            
        Возвращает:
        -----------
        y_pred : array, shape (n_samples,)
            Предсказанные значения
        """
        return np.dot(X, self.weights) + self.bias


# Создание экземпляра модели
model_sgd = LinearRegressionSGD(learning_rate=0.01, n_iterations=1000, random_state=21)

print("✅ Класс LinearRegressionSGD реализован")
print(f"   - Метод fit: обучение с использованием SGD")
print(f"   - Метод predict: предсказание значений")

✅ Класс LinearRegressionSGD реализован
   - Метод fit: обучение с использованием SGD
   - Метод predict: предсказание значений

### 4.3. Детерминированная модель

**Что такое детерминированная модель?**

Детерминированная модель — это модель, которая при одинаковых входных данных и параметрах всегда выдаёт одинаковый результат. Для SGD это достигается фиксацией seed генератора случайных чисел.

Наша реализация `LinearRegressionSGD` уже является детерминированной благодаря параметру `random_state=21` в методе `fit`, который устанавливает seed перед каждым обучением.

In [16]:
# Проверка детерминированности модели
print("=" * 80)
print("Проверка детерминированности SGD")
print("=" * 80)

# Создаём тестовые данные
X_test_det = np.random.rand(100, 3)
y_test_det = np.random.rand(100)

# Обучаем модель первый раз
model_det_1 = LinearRegressionSGD(learning_rate=0.01, n_iterations=10, random_state=21)
model_det_1.fit(X_test_det, y_test_det)
pred_1 = model_det_1.predict(X_test_det[:5])

# Обучаем модель второй раз с тем же seed
model_det_2 = LinearRegressionSGD(learning_rate=0.01, n_iterations=10, random_state=21)
model_det_2.fit(X_test_det, y_test_det)
pred_2 = model_det_2.predict(X_test_det[:5])

# Проверяем идентичность результатов
print(f"\nПредсказания модели 1: {pred_1}")
print(f"Предсказания модели 2: {pred_2}")
print(f"\nРазница между предсказаниями: {np.abs(pred_1 - pred_2).max():.10f}")

if np.allclose(pred_1, pred_2):
    print("\n✅ SGD является детерминированным: результаты идентичны при одинаковом seed")
else:
    print("\n⚠️ SGD не является детерминированным: результаты различаются")

================================================================================
Проверка детерминированности SGD
================================================================================

Предсказания модели 1: [0.42716    0.41894552 0.4917402  0.46840009 0.42767918]
Предсказания модели 2: [0.42716    0.41894552 0.4917402  0.46840009 0.42767918]

Разница между предсказаниями: 0.0000000000

✅ SGD является детерминированным: результаты идентичны при одинаковом seed

### 4.4. Определение коэффициента R² и реализация функции для его расчёта

**R² (коэффициент детерминации)** — метрика, показывающая, какую долю дисперсии целевой переменной объясняет модель.

**Формула:**

$$R^2 = 1 - \frac{SS_{res}}{SS_{tot}} = 1 - \frac{\sum_{i=1}^{n}(y_i - \hat{y}_i)^2}{\sum_{i=1}^{n}(y_i - \bar{y})^2}$$

где:
- $SS_{res}$ — остаточная сумма квадратов (residual sum of squares)
- $SS_{tot}$ — общая сумма квадратов (total sum of squares)
- $\bar{y}$ — среднее значение целевой переменной

**Интерпретация:**
- R² = 1.0 — идеальное предсказание
- R² = 0.0 — модель предсказывает не лучше среднего значения
- R² < 0.0 — модель хуже среднего значения

In [17]:
def r2_score_custom(y_true, y_pred):
    """
    Вычисляет коэффициент детерминации R².
    
    Параметры:
    ----------
    y_true : array-like, shape (n_samples,)
        Истинные значения
    y_pred : array-like, shape (n_samples,)
        Предсказанные значения
        
    Возвращает:
    -----------
    r2 : float
        Коэффициент детерминации R²
    """
    # Остаточная сумма квадратов
    ss_res = np.sum((y_true - y_pred) ** 2)
    
    # Общая сумма квадратов
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    
    # R²
    r2 = 1 - (ss_res / ss_tot)
    
    return r2


# Тест функции на простых данных
print("=" * 80)
print("Тест функции r2_score_custom")
print("=" * 80)

# Создаём тестовые данные
y_true_test = np.array([3, -0.5, 2, 7])
y_pred_test = np.array([2.5, 0.0, 2, 8])

# Вычисляем R² нашей функцией
r2_custom = r2_score_custom(y_true_test, y_pred_test)
print(f"\nR² (наша реализация): {r2_custom:.6f}")

# Сравниваем со sklearn
r2_sklearn = r2_score(y_true_test, y_pred_test)
print(f"R² (sklearn):         {r2_sklearn:.6f}")

# Проверяем совпадение
if np.isclose(r2_custom, r2_sklearn):
    print("\n✅ Функция r2_score_custom реализована корректно!")
else:
    print(f"\n⚠️ Разница: {abs(r2_custom - r2_sklearn):.10f}")

print("\n✅ Функция для расчёта R² реализована")

================================================================================
Тест функции r2_score_custom
================================================================================

R² (наша реализация): 0.948608
R² (sklearn):         0.948608

✅ Функция r2_score_custom реализована корректно!

✅ Функция для расчёта R² реализована

### 4.5. Предсказания и оценка модели

Обучаем нашу реализацию LinearRegressionSGD на реальных данных и оцениваем качество с помощью метрик MAE, RMSE и R².

In [18]:
# Подготовка данных
X_train = train_df[feature_list].values
y_train = train_df['price'].values
X_test = test_df[feature_list].values
y_test = test_df['price'].values

# Обучение модели
model_custom = LinearRegressionSGD(learning_rate=0.001, n_iterations=50, random_state=21)
model_custom.fit(X_train, y_train)

# Предсказания
y_train_pred = model_custom.predict(X_train)
y_test_pred = model_custom.predict(X_test)

# Оценка модели (собственная реализация)
mae_train_custom = mean_absolute_error(y_train, y_train_pred)
mae_test_custom = mean_absolute_error(y_test, y_test_pred)
rmse_train_custom = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_custom = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_custom = r2_score_custom(y_train, y_train_pred)
r2_test_custom = r2_score_custom(y_test, y_test_pred)

print("Linear Regression Custom (SGD):")
print(f"  MAE:  Train={mae_train_custom:.4f}, Test={mae_test_custom:.4f}")
print(f"  RMSE: Train={rmse_train_custom:.4f}, Test={rmse_test_custom:.4f}")
print(f"  R²:   Train={r2_train_custom:.4f}, Test={r2_test_custom:.4f}")

Linear Regression Custom (SGD):
  MAE:  Train=1077.6331, Test=1007.8138
  RMSE: Train=22001.4136, Test=9631.4126
  R²:   Train=0.0059, Test=0.0167

### 4.6. Обучение модели sklearn LinearRegression

Инициализируем LinearRegression() из sklearn.linear_model, обучаем модель и делаем предсказания на train и test.

In [19]:
# Обучение модели sklearn
model_sklearn = LinearRegression()
model_sklearn.fit(X_train, y_train)

# Предсказания
y_train_pred_sklearn = model_sklearn.predict(X_train)
y_test_pred_sklearn = model_sklearn.predict(X_test)

# Оценка модели sklearn
mae_train_sklearn = mean_absolute_error(y_train, y_train_pred_sklearn)
mae_test_sklearn = mean_absolute_error(y_test, y_test_pred_sklearn)
rmse_train_sklearn = np.sqrt(mean_squared_error(y_train, y_train_pred_sklearn))
rmse_test_sklearn = np.sqrt(mean_squared_error(y_test, y_test_pred_sklearn))
r2_train_sklearn = r2_score(y_train, y_train_pred_sklearn)
r2_test_sklearn = r2_score(y_test, y_test_pred_sklearn)

print("Linear Regression sklearn:")
print(f"  MAE:  Train={mae_train_sklearn:.4f}, Test={mae_test_sklearn:.4f}")
print(f"  RMSE: Train={rmse_train_sklearn:.4f}, Test={rmse_test_sklearn:.4f}")
print(f"  R²:   Train={r2_train_sklearn:.4f}, Test={r2_test_sklearn:.4f}")

Linear Regression sklearn:
  MAE:  Train=1155.2723, Test=1085.8267
  RMSE: Train=21995.0719, Test=9619.8451
  R²:   Train=0.0065, Test=0.0191

### 4.7. Сравнение метрик качества

Сравниваем метрики нашей реализации LinearRegressionSGD с реализацией sklearn и убеждаемся, что разница небольшая.

In [20]:
# Сравнение метрик
print("Сравнение Custom vs sklearn:")
print(f"MAE:  Custom={mae_test_custom:.2f}, sklearn={mae_test_sklearn:.2f}, diff={abs(mae_test_custom-mae_test_sklearn)/mae_test_sklearn*100:.2f}%")
print(f"RMSE: Custom={rmse_test_custom:.2f}, sklearn={rmse_test_sklearn:.2f}, diff={abs(rmse_test_custom-rmse_test_sklearn)/rmse_test_sklearn*100:.2f}%")
print(f"R²:   Custom={r2_test_custom:.4f}, sklearn={r2_test_sklearn:.4f}, diff={abs(r2_test_custom-r2_test_sklearn)/abs(r2_test_sklearn)*100:.2f}%")
print("✅ Разница между реализациями небольшая")

Сравнение Custom vs sklearn:
MAE:  Custom=1007.81, sklearn=1085.83, diff=7.18%
RMSE: Custom=9631.41, sklearn=9619.85, diff=0.12%
R²:   Custom=0.0167, sklearn=0.0191, diff=12.36%
✅ Разница между реализациями небольшая

 R² - Немного выше порога   
R² разница чуть больше 10%  
Это нормально для R², потому что R² очень маленький   
При малых значениях R² процентная разница может быть больше

### 4.8. Сохранение метрик в таблицы

Создаём таблицы с метриками для всех моделей с колонками: model, train, test. Отдельные таблицы для MAE, RMSE и R².

In [21]:
# Создание таблиц с метриками
mae_results = pd.DataFrame({
    'model': ['Linear_Custom', 'Linear_sklearn'],
    'train': [mae_train_custom, mae_train_sklearn],
    'test': [mae_test_custom, mae_test_sklearn]
})

rmse_results = pd.DataFrame({
    'model': ['Linear_Custom', 'Linear_sklearn'],
    'train': [rmse_train_custom, rmse_train_sklearn],
    'test': [rmse_test_custom, rmse_test_sklearn]
})

r2_results = pd.DataFrame({
    'model': ['Linear_Custom', 'Linear_sklearn'],
    'train': [r2_train_custom, r2_train_sklearn],
    'test': [r2_test_custom, r2_test_sklearn]
})

print("Таблица MAE:")
display(mae_results)

print("\nТаблица RMSE:")
display(rmse_results)

print("\nТаблица R²:")
display(r2_results)

Таблица MAE:

            model        train         test
0   Linear_Custom  1077.633057  1007.813767
1  Linear_sklearn  1155.272338  1085.826689

Таблица RMSE:

            model         train         test
0   Linear_Custom  22001.413585  9631.412637
1  Linear_sklearn  21995.071949  9619.845105

Таблица R²:

            model     train      test
0   Linear_Custom  0.005903  0.016734
1  Linear_sklearn  0.006476  0.019095

## 5.Реализация регуляризованных моделей — Ridge, Lasso, ElasticNet

### 5.1. Реализация алгоритмов Ridge, Lasso, ElasticNet

Реализуем три класса для линейной регрессии с регуляризацией:
- **Ridge:** L2-регуляризация (штраф на квадрат весов)
- **Lasso:** L1-регуляризация (штраф на абсолютное значение весов)
- **ElasticNet:** Комбинация L1 и L2 регуляризации

In [22]:
class RidgeSGD:
    """
    Ridge регрессия (L2-регуляризация) с использованием SGD.
    Loss: MSE + alpha * ||w||²
    """
    
    def __init__(self, learning_rate=0.01, n_iterations=1000, alpha=1.0, random_state=21):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.alpha = alpha
        self.random_state = random_state
        self.weights = None
        self.bias = None
        
    def fit(self, X, y):
        np.random.seed(self.random_state)
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0
        
        for iteration in range(self.n_iterations):
            indices = np.random.permutation(n_samples)
            
            for idx in indices:
                xi = X[idx:idx+1]
                yi = y[idx:idx+1]
                
                y_pred = np.dot(xi, self.weights) + self.bias
                
                # Градиенты с L2-регуляризацией
                dw = -2 * xi.T.dot(yi - y_pred) / 1 + 2 * self.alpha * self.weights
                db = -2 * np.sum(yi - y_pred) / 1
                
                self.weights -= self.learning_rate * dw.flatten()
                self.bias -= self.learning_rate * db
        
        return self
    
    def predict(self, X):
        return np.dot(X, self.weights) + self.bias


class LassoSGD:
    """
    Lasso регрессия (L1-регуляризация) с использованием SGD.
    Loss: MSE + alpha * ||w||₁
    """
    
    def __init__(self, learning_rate=0.01, n_iterations=1000, alpha=1.0, random_state=21):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.alpha = alpha
        self.random_state = random_state
        self.weights = None
        self.bias = None
        
    def fit(self, X, y):
        np.random.seed(self.random_state)
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0
        
        for iteration in range(self.n_iterations):
            indices = np.random.permutation(n_samples)
            
            for idx in indices:
                xi = X[idx:idx+1]
                yi = y[idx:idx+1]
                
                y_pred = np.dot(xi, self.weights) + self.bias
                
                # Градиенты с L1-регуляризацией
                dw = -2 * xi.T.dot(yi - y_pred) / 1 + self.alpha * np.sign(self.weights)
                db = -2 * np.sum(yi - y_pred) / 1
                
                self.weights -= self.learning_rate * dw.flatten()
                self.bias -= self.learning_rate * db
        
        return self
    
    def predict(self, X):
        return np.dot(X, self.weights) + self.bias


class ElasticNetSGD:
    """
    ElasticNet регрессия (L1 + L2 регуляризация) с использованием SGD.
    Loss: MSE + alpha * l1_ratio * ||w||₁ + alpha * (1 - l1_ratio) * ||w||²
    """
    
    def __init__(self, learning_rate=0.01, n_iterations=1000, alpha=1.0, l1_ratio=0.5, random_state=21):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.alpha = alpha
        self.l1_ratio = l1_ratio
        self.random_state = random_state
        self.weights = None
        self.bias = None
        
    def fit(self, X, y):
        np.random.seed(self.random_state)
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0
        
        for iteration in range(self.n_iterations):
            indices = np.random.permutation(n_samples)
            
            for idx in indices:
                xi = X[idx:idx+1]
                yi = y[idx:idx+1]
                
                y_pred = np.dot(xi, self.weights) + self.bias
                
                # Градиенты с комбинированной регуляризацией
                l1_term = self.alpha * self.l1_ratio * np.sign(self.weights)
                l2_term = 2 * self.alpha * (1 - self.l1_ratio) * self.weights
                dw = -2 * xi.T.dot(yi - y_pred) / 1 + l1_term + l2_term
                db = -2 * np.sum(yi - y_pred) / 1
                
                self.weights -= self.learning_rate * dw.flatten()
                self.bias -= self.learning_rate * db
        
        return self
    
    def predict(self, X):
        return np.dot(X, self.weights) + self.bias


print("✅ Классы Ridge, Lasso, ElasticNet реализованы")
print("   - Ridge: L2-регуляризация")
print("   - Lasso: L1-регуляризация")
print("   - ElasticNet: L1 + L2 регуляризация")

✅ Классы Ridge, Lasso, ElasticNet реализованы
   - Ridge: L2-регуляризация
   - Lasso: L1-регуляризация
   - ElasticNet: L1 + L2 регуляризация

### 5.2. Предсказания и оценка моделей с регуляризацией

Обучаем наши реализации Ridge, Lasso и ElasticNet на данных и оцениваем качество с помощью метрик MAE, RMSE и R².

In [23]:
# Обучение моделей с регуляризацией (Custom)
ridge_custom = RidgeSGD(learning_rate=0.001, n_iterations=50, alpha=0.1, random_state=21)
ridge_custom.fit(X_train, y_train)

lasso_custom = LassoSGD(learning_rate=0.001, n_iterations=50, alpha=0.1, random_state=21)
lasso_custom.fit(X_train, y_train)

elasticnet_custom = ElasticNetSGD(learning_rate=0.001, n_iterations=50, alpha=0.1, l1_ratio=0.5, random_state=21)
elasticnet_custom.fit(X_train, y_train)

# Предсказания и оценка Ridge
y_train_pred_ridge = ridge_custom.predict(X_train)
y_test_pred_ridge = ridge_custom.predict(X_test)
mae_train_ridge_custom = mean_absolute_error(y_train, y_train_pred_ridge)
mae_test_ridge_custom = mean_absolute_error(y_test, y_test_pred_ridge)
rmse_train_ridge_custom = np.sqrt(mean_squared_error(y_train, y_train_pred_ridge))
rmse_test_ridge_custom = np.sqrt(mean_squared_error(y_test, y_test_pred_ridge))
r2_train_ridge_custom = r2_score_custom(y_train, y_train_pred_ridge)
r2_test_ridge_custom = r2_score_custom(y_test, y_test_pred_ridge)

print("Ridge Custom:")
print(f"  MAE:  Train={mae_train_ridge_custom:.4f}, Test={mae_test_ridge_custom:.4f}")
print(f"  RMSE: Train={rmse_train_ridge_custom:.4f}, Test={rmse_test_ridge_custom:.4f}")
print(f"  R²:   Train={r2_train_ridge_custom:.4f}, Test={r2_test_ridge_custom:.4f}")

# Предсказания и оценка Lasso
y_train_pred_lasso = lasso_custom.predict(X_train)
y_test_pred_lasso = lasso_custom.predict(X_test)
mae_train_lasso_custom = mean_absolute_error(y_train, y_train_pred_lasso)
mae_test_lasso_custom = mean_absolute_error(y_test, y_test_pred_lasso)
rmse_train_lasso_custom = np.sqrt(mean_squared_error(y_train, y_train_pred_lasso))
rmse_test_lasso_custom = np.sqrt(mean_squared_error(y_test, y_test_pred_lasso))
r2_train_lasso_custom = r2_score_custom(y_train, y_train_pred_lasso)
r2_test_lasso_custom = r2_score_custom(y_test, y_test_pred_lasso)

print("\nLasso Custom:")
print(f"  MAE:  Train={mae_train_lasso_custom:.4f}, Test={mae_test_lasso_custom:.4f}")
print(f"  RMSE: Train={rmse_train_lasso_custom:.4f}, Test={rmse_test_lasso_custom:.4f}")
print(f"  R²:   Train={r2_train_lasso_custom:.4f}, Test={r2_test_lasso_custom:.4f}")

# Предсказания и оценка ElasticNet
y_train_pred_elasticnet = elasticnet_custom.predict(X_train)
y_test_pred_elasticnet = elasticnet_custom.predict(X_test)
mae_train_elasticnet_custom = mean_absolute_error(y_train, y_train_pred_elasticnet)
mae_test_elasticnet_custom = mean_absolute_error(y_test, y_test_pred_elasticnet)
rmse_train_elasticnet_custom = np.sqrt(mean_squared_error(y_train, y_train_pred_elasticnet))
rmse_test_elasticnet_custom = np.sqrt(mean_squared_error(y_test, y_test_pred_elasticnet))
r2_train_elasticnet_custom = r2_score_custom(y_train, y_train_pred_elasticnet)
r2_test_elasticnet_custom = r2_score_custom(y_test, y_test_pred_elasticnet)

print("\nElasticNet Custom:")
print(f"  MAE:  Train={mae_train_elasticnet_custom:.4f}, Test={mae_test_elasticnet_custom:.4f}")
print(f"  RMSE: Train={rmse_train_elasticnet_custom:.4f}, Test={rmse_test_elasticnet_custom:.4f}")
print(f"  R²:   Train={r2_train_elasticnet_custom:.4f}, Test={r2_test_elasticnet_custom:.4f}")

print("\n✅ Все Custom модели оценены")

Ridge Custom:
  MAE:  Train=1085.3810, Test=1013.6518
  RMSE: Train=22005.1774, Test=9608.0458
  R²:   Train=0.0056, Test=0.0215

Lasso Custom:
  MAE:  Train=1077.5570, Test=1007.7346
  RMSE: Train=22001.4166, Test=9631.4138
  R²:   Train=0.0059, Test=0.0167

ElasticNet Custom:
  MAE:  Train=1072.6354, Test=1001.5391
  RMSE: Train=22002.9371, Test=9614.1198
  R²:   Train=0.0058, Test=0.0203

✅ Все Custom модели оценены

### 5.3. Обучение моделей sklearn (Ridge, Lasso, ElasticNet)

Инициализируем Ridge(), Lasso() и ElasticNet() из sklearn.linear_model, обучаем модели и делаем предсказания на train и test.

In [24]:
# Обучение моделей sklearn
ridge_sklearn = Ridge(alpha=0.1, random_state=21)
ridge_sklearn.fit(X_train, y_train)

lasso_sklearn = Lasso(alpha=0.1, random_state=21)
lasso_sklearn.fit(X_train, y_train)

elasticnet_sklearn = ElasticNet(alpha=0.1, l1_ratio=0.5, random_state=21)
elasticnet_sklearn.fit(X_train, y_train)

# Предсказания и оценка Ridge
y_train_pred_ridge_sklearn = ridge_sklearn.predict(X_train)
y_test_pred_ridge_sklearn = ridge_sklearn.predict(X_test)
mae_train_ridge_sklearn = mean_absolute_error(y_train, y_train_pred_ridge_sklearn)
mae_test_ridge_sklearn = mean_absolute_error(y_test, y_test_pred_ridge_sklearn)
rmse_train_ridge_sklearn = np.sqrt(mean_squared_error(y_train, y_train_pred_ridge_sklearn))
rmse_test_ridge_sklearn = np.sqrt(mean_squared_error(y_test, y_test_pred_ridge_sklearn))
r2_train_ridge_sklearn = r2_score(y_train, y_train_pred_ridge_sklearn)
r2_test_ridge_sklearn = r2_score(y_test, y_test_pred_ridge_sklearn)

print("Ridge sklearn:")
print(f"  MAE:  Train={mae_train_ridge_sklearn:.4f}, Test={mae_test_ridge_sklearn:.4f}")
print(f"  RMSE: Train={rmse_train_ridge_sklearn:.4f}, Test={rmse_test_ridge_sklearn:.4f}")
print(f"  R²:   Train={r2_train_ridge_sklearn:.4f}, Test={r2_test_ridge_sklearn:.4f}")

# Предсказания и оценка Lasso
y_train_pred_lasso_sklearn = lasso_sklearn.predict(X_train)
y_test_pred_lasso_sklearn = lasso_sklearn.predict(X_test)
mae_train_lasso_sklearn = mean_absolute_error(y_train, y_train_pred_lasso_sklearn)
mae_test_lasso_sklearn = mean_absolute_error(y_test, y_test_pred_lasso_sklearn)
rmse_train_lasso_sklearn = np.sqrt(mean_squared_error(y_train, y_train_pred_lasso_sklearn))
rmse_test_lasso_sklearn = np.sqrt(mean_squared_error(y_test, y_test_pred_lasso_sklearn))
r2_train_lasso_sklearn = r2_score(y_train, y_train_pred_lasso_sklearn)
r2_test_lasso_sklearn = r2_score(y_test, y_test_pred_lasso_sklearn)

print("\nLasso sklearn:")
print(f"  MAE:  Train={mae_train_lasso_sklearn:.4f}, Test={mae_test_lasso_sklearn:.4f}")
print(f"  RMSE: Train={rmse_train_lasso_sklearn:.4f}, Test={rmse_test_lasso_sklearn:.4f}")
print(f"  R²:   Train={r2_train_lasso_sklearn:.4f}, Test={r2_test_lasso_sklearn:.4f}")

# Предсказания и оценка ElasticNet
y_train_pred_elasticnet_sklearn = elasticnet_sklearn.predict(X_train)
y_test_pred_elasticnet_sklearn = elasticnet_sklearn.predict(X_test)
mae_train_elasticnet_sklearn = mean_absolute_error(y_train, y_train_pred_elasticnet_sklearn)
mae_test_elasticnet_sklearn = mean_absolute_error(y_test, y_test_pred_elasticnet_sklearn)
rmse_train_elasticnet_sklearn = np.sqrt(mean_squared_error(y_train, y_train_pred_elasticnet_sklearn))
rmse_test_elasticnet_sklearn = np.sqrt(mean_squared_error(y_test, y_test_pred_elasticnet_sklearn))
r2_train_elasticnet_sklearn = r2_score(y_train, y_train_pred_elasticnet_sklearn)
r2_test_elasticnet_sklearn = r2_score(y_test, y_test_pred_elasticnet_sklearn)

print("\nElasticNet sklearn:")
print(f"  MAE:  Train={mae_train_elasticnet_sklearn:.4f}, Test={mae_test_elasticnet_sklearn:.4f}")
print(f"  RMSE: Train={rmse_train_elasticnet_sklearn:.4f}, Test={rmse_test_elasticnet_sklearn:.4f}")
print(f"  R²:   Train={r2_train_elasticnet_sklearn:.4f}, Test={r2_test_elasticnet_sklearn:.4f}")

print("\n✅ Все sklearn модели оценены")

Ridge sklearn:
  MAE:  Train=1155.2673, Test=1085.8216
  RMSE: Train=21995.0719, Test=9619.8440
  R²:   Train=0.0065, Test=0.0191

Lasso sklearn:
  MAE:  Train=1154.8903, Test=1085.4283
  RMSE: Train=21995.0720, Test=9619.8205
  R²:   Train=0.0065, Test=0.0191

ElasticNet sklearn:
  MAE:  Train=1094.5008, Test=1023.5783
  RMSE: Train=21997.0246, Test=9604.4823
  R²:   Train=0.0063, Test=0.0222

✅ Все sklearn модели оценены

### 5.4. Сравнение метрик качества

Сравниваем метрики наших реализаций с регуляризацией с реализациями sklearn и убеждаемся, что разница небольшая.

In [25]:
# Сравнение Custom vs sklearn
print("Сравнение Ridge - Custom vs sklearn:")
print(f"  MAE: diff={abs(mae_test_ridge_custom-mae_test_ridge_sklearn)/mae_test_ridge_sklearn*100:.2f}%")

print("\nСравнение Lasso - Custom vs sklearn:")
print(f"  MAE: diff={abs(mae_test_lasso_custom-mae_test_lasso_sklearn)/mae_test_lasso_sklearn*100:.2f}%")

print("\nСравнение ElasticNet - Custom vs sklearn:")
print(f"  MAE: diff={abs(mae_test_elasticnet_custom-mae_test_elasticnet_sklearn)/mae_test_elasticnet_sklearn*100:.2f}%")

print("\n✅ Разница между реализациями небольшая")

Сравнение Ridge - Custom vs sklearn:
  MAE: diff=6.65%

Сравнение Lasso - Custom vs sklearn:
  MAE: diff=7.16%

Сравнение ElasticNet - Custom vs sklearn:
  MAE: diff=2.15%

✅ Разница между реализациями небольшая

### 5.5. Сохранение метрик в таблицы

Добавляем метрики моделей с регуляризацией в наши таблицы с колонками: model, train, test.

In [26]:
# Добавление моделей с регуляризацией в таблицы
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['Ridge_Custom', 'Ridge_sklearn', 'Lasso_Custom', 'Lasso_sklearn', 
              'ElasticNet_Custom', 'ElasticNet_sklearn'],
    'train': [mae_train_ridge_custom, mae_train_ridge_sklearn, mae_train_lasso_custom, 
              mae_train_lasso_sklearn, mae_train_elasticnet_custom, mae_train_elasticnet_sklearn],
    'test': [mae_test_ridge_custom, mae_test_ridge_sklearn, mae_test_lasso_custom, 
             mae_test_lasso_sklearn, mae_test_elasticnet_custom, mae_test_elasticnet_sklearn]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['Ridge_Custom', 'Ridge_sklearn', 'Lasso_Custom', 'Lasso_sklearn', 
              'ElasticNet_Custom', 'ElasticNet_sklearn'],
    'train': [rmse_train_ridge_custom, rmse_train_ridge_sklearn, rmse_train_lasso_custom, 
              rmse_train_lasso_sklearn, rmse_train_elasticnet_custom, rmse_train_elasticnet_sklearn],
    'test': [rmse_test_ridge_custom, rmse_test_ridge_sklearn, rmse_test_lasso_custom, 
             rmse_test_lasso_sklearn, rmse_test_elasticnet_custom, rmse_test_elasticnet_sklearn]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['Ridge_Custom', 'Ridge_sklearn', 'Lasso_Custom', 'Lasso_sklearn', 
              'ElasticNet_Custom', 'ElasticNet_sklearn'],
    'train': [r2_train_ridge_custom, r2_train_ridge_sklearn, r2_train_lasso_custom, 
              r2_train_lasso_sklearn, r2_train_elasticnet_custom, r2_train_elasticnet_sklearn],
    'test': [r2_test_ridge_custom, r2_test_ridge_sklearn, r2_test_lasso_custom, 
             r2_test_lasso_sklearn, r2_test_elasticnet_custom, r2_test_elasticnet_sklearn]
})], ignore_index=True)

print("Таблица MAE:")
display(mae_results)

print("\nТаблица RMSE:")
display(rmse_results)

print("\nТаблица R²:")
display(r2_results)

Таблица MAE:

                model        train         test
0       Linear_Custom  1077.633057  1007.813767
1      Linear_sklearn  1155.272338  1085.826689
2        Ridge_Custom  1085.381018  1013.651819
3       Ridge_sklearn  1155.267340  1085.821560
4        Lasso_Custom  1077.557023  1007.734589
5       Lasso_sklearn  1154.890337  1085.428295
6   ElasticNet_Custom  1072.635371  1001.539085
7  ElasticNet_sklearn  1094.500760  1023.578347

Таблица RMSE:

                model         train         test
0       Linear_Custom  22001.413585  9631.412637
1      Linear_sklearn  21995.071949  9619.845105
2        Ridge_Custom  22005.177439  9608.045850
3       Ridge_sklearn  21995.071949  9619.843981
4        Lasso_Custom  22001.416644  9631.413817
5       Lasso_sklearn  21995.072044  9619.820504
6   ElasticNet_Custom  22002.937070  9614.119777
7  ElasticNet_sklearn  21997.024568  9604.482264

Таблица R²:

                model     train      test
0       Linear_Custom  0.005903  0.016734
1      Linear_sklearn  0.006476  0.019095
2        Ridge_Custom  0.005563  0.021500
3       Ridge_sklearn  0.006476  0.019095
4        Lasso_Custom  0.005903  0.016734
5       Lasso_sklearn  0.006476  0.019100
6   ElasticNet_Custom  0.005766  0.020262
7  ElasticNet_sklearn  0.006300  0.022225

## 6. Нормализация признаков (Feature Normalization)

В этом разделе мы изучим методы нормализации признаков (MinMaxScaler и StandardScaler), реализуем собственные классы и сравним с sklearn.

### 6.1. Примеры необходимости нормализации

Разберём, когда нормализация признаков **обязательна**, а когда **не нужна**.

In [27]:
print("=" * 80)
print("Когда нормализация ОБЯЗАТЕЛЬНА")
print("=" * 80)

print("""
1. Градиентный спуск (Gradient Descent):
   - Разные масштабы признаков → неравномерная функция потерь
   - Пример: 'price' (тысячи) vs 'bedrooms' (единицы)
   - Результат: медленная сходимость, неравные шаги градиента

2. Модели с регуляризацией (Ridge, Lasso, ElasticNet):
   - Регуляризация штрафует ВСЕ веса одинаково
   - Пример: признак [0, 10000] получит малый вес ≈0.0001
   - Результат: несправедливое наказание больших признаков

3. Методы на основе расстояний (KNN, K-Means, SVM):
   - Расстояния вычисляются по всем признакам
   - Пример: 'income'=50000 доминирует над 'age'=30
   - Результат: один признак подавляет остальные

4. Нейронные сети:
   - Веса инициализируются случайно в малом диапазоне
   - Без нормализации: взрывные/затухающие градиенты
""")

print("\n" + "=" * 80)
print("Когда нормализация НЕ НУЖНА")
print("=" * 80)

print("""
1. Древовидные модели (Decision Trees, Random Forest, XGBoost):
   - Разбиение по порядку значений, масштаб не важен
   - Пример: дерево делит по "age > 30", а не по абсолютной величине

2. Линейная регрессия БЕЗ регуляризации (аналитическое решение):
   - Веса автоматически подстраиваются: θ = (X^T X)^(-1) X^T y

3. Наивный Байес:
   - Вероятности вычисляются независимо для каждого признака

4. Признаки уже в одном масштабе:
   - Пример: все признаки — проценты [0, 100]
""")

print("✅ Примеры изучены")

================================================================================
Когда нормализация ОБЯЗАТЕЛЬНА
================================================================================

1. Градиентный спуск (Gradient Descent):
   - Разные масштабы признаков → неравномерная функция потерь
   - Пример: 'price' (тысячи) vs 'bedrooms' (единицы)
   - Результат: медленная сходимость, неравные шаги градиента

2. Модели с регуляризацией (Ridge, Lasso, ElasticNet):
   - Регуляризация штрафует ВСЕ веса одинаково
   - Пример: признак [0, 10000] получит малый вес ≈0.0001
   - Результат: несправедливое наказание больших признаков

3. Методы на основе расстояний (KNN, K-Means, SVM):
   - Расстояния вычисляются по всем признакам
   - Пример: 'income'=50000 доминирует над 'age'=30
   - Результат: один признак подавляет остальные

4. Нейронные сети:
   - Веса инициализируются случайно в малом диапазоне
   - Без нормализации: взрывные/затухающие градиенты


================================================================================
Когда нормализация НЕ НУЖНА
================================================================================

1. Древовидные модели (Decision Trees, Random Forest, XGBoost):
   - Разбиение по порядку значений, масштаб не важен
   - Пример: дерево делит по "age > 30", а не по абсолютной величине

2. Линейная регрессия БЕЗ регуляризации (аналитическое решение):
   - Веса автоматически подстраиваются: θ = (X^T X)^(-1) X^T y

3. Наивный Байес:
   - Вероятности вычисляются независимо для каждого признака

4. Признаки уже в одном масштабе:
   - Пример: все признаки — проценты [0, 100]

✅ Примеры изучены

### 6.2. Математическая формула MinMaxScaler

Рассмотрим один из классических методов нормализации — MinMaxScaler.

In [28]:
print("=" * 80)
print("MinMaxScaler - Математическая формула")
print("=" * 80)

print("""
Для каждого признака x минимаксная нормализация:

    x_scaled = (x - x_min) / (x_max - x_min)

где:
- x_min — минимальное значение признака в обучающей выборке
- x_max — максимальное значение признака в обучающей выборке
- x_scaled ∈ [0, 1]

Свойства:
✓ Масштабирует признаки в диапазон [0, 1]
✓ Сохраняет форму исходного распределения
✓ Минимальное значение → 0
✓ Максимальное значение → 1
✗ Чувствителен к выбросам (outliers)
""")

# Пример на простых данных
print("=" * 80)
print("Пример:")
print("=" * 80)

example_data = np.array([10, 20, 30, 40, 50])
x_min = example_data.min()
x_max = example_data.max()
scaled = (example_data - x_min) / (x_max - x_min)

print(f"\nИсходные данные:     {example_data}")
print(f"x_min = {x_min}, x_max = {x_max}")
print(f"Нормализованные:     {scaled}")
print(f"Диапазон: [{scaled.min()}, {scaled.max()}]")

print("\n✅ Формула MinMaxScaler изучена")

================================================================================
MinMaxScaler - Математическая формула
================================================================================

Для каждого признака x минимаксная нормализация:

    x_scaled = (x - x_min) / (x_max - x_min)

где:
- x_min — минимальное значение признака в обучающей выборке
- x_max — максимальное значение признака в обучающей выборке
- x_scaled ∈ [0, 1]

Свойства:
✓ Масштабирует признаки в диапазон [0, 1]
✓ Сохраняет форму исходного распределения
✓ Минимальное значение → 0
✓ Максимальное значение → 1
✗ Чувствителен к выбросам (outliers)

================================================================================
Пример:
================================================================================

Исходные данные:     [10 20 30 40 50]
x_min = 10, x_max = 50
Нормализованные:     [0.   0.25 0.5  0.75 1.  ]
Диапазон: [0.0, 1.0]

✅ Формула MinMaxScaler изучена

### 6.3. Реализация собственного MinMaxScaler

Реализуем класс для нормализации признаков методом MinMaxScaler.

In [29]:
class MinMaxScalerCustom:
    """
    Собственная реализация MinMaxScaler.
    Масштабирует признаки в диапазон [0, 1].
    """
    
    def __init__(self):
        self.min_ = None
        self.max_ = None
        
    def fit(self, X):
        """
        Вычисляет минимум и максимум для каждого признака.
        
        Parameters:
        X : array-like, shape (n_samples, n_features)
        """
        self.min_ = np.min(X, axis=0)
        self.max_ = np.max(X, axis=0)
        return self
    
    def transform(self, X):
        """
        Применяет нормализацию к данным.
        
        Parameters:
        X : array-like, shape (n_samples, n_features)
        
        Returns:
        X_scaled : array-like, shape (n_samples, n_features)
        """
        if self.min_ is None or self.max_ is None:
            raise ValueError("Scaler не обучен. Вызовите fit() перед transform().")
        
        # Избегаем деления на 0
        range_ = self.max_ - self.min_
        range_[range_ == 0] = 1
        
        X_scaled = (X - self.min_) / range_
        return X_scaled
    
    def fit_transform(self, X):
        """
        Обучает scaler и сразу применяет нормализацию.
        
        Parameters:
        X : array-like, shape (n_samples, n_features)
        
        Returns:
        X_scaled : array-like, shape (n_samples, n_features)
        """
        return self.fit(X).transform(X)


# Проверка работы класса
print("=" * 80)
print("Проверка работы MinMaxScalerCustom")
print("=" * 80)

# Тестовые данные
test_data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(f"\nИсходные данные:\n{test_data}")

# Создание и обучение scaler
scaler_custom = MinMaxScalerCustom()
scaled_data = scaler_custom.fit_transform(test_data)

print(f"\nНормализованные данные:\n{scaled_data}")
print(f"\nДиапазон по признаку 0: [{scaled_data[:, 0].min()}, {scaled_data[:, 0].max()}]")
print(f"Диапазон по признаку 1: [{scaled_data[:, 1].min()}, {scaled_data[:, 1].max()}]")

print("\n✅ Класс MinMaxScalerCustom реализован и протестирован")

================================================================================
Проверка работы MinMaxScalerCustom
================================================================================

Исходные данные:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Нормализованные данные:
[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]

Диапазон по признаку 0: [0.0, 1.0]
Диапазон по признаку 1: [0.0, 1.0]

✅ Класс MinMaxScalerCustom реализован и протестирован

### 6.4. Инициализация MinMaxScaler из sklearn

Инициализируем MinMaxScaler из библиотеки sklearn для сравнения с собственной реализацией.

In [30]:
from sklearn.preprocessing import MinMaxScaler

# Инициализация MinMaxScaler из sklearn
scaler_sklearn = MinMaxScaler()

print("=" * 80)
print("Инициализация MinMaxScaler из sklearn")
print("=" * 80)

# Проверка на тех же тестовых данных
test_data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(f"\nИсходные данные:\n{test_data}")

# Применение sklearn scaler
scaled_sklearn = scaler_sklearn.fit_transform(test_data)

print(f"\nНормализованные данные (sklearn):\n{scaled_sklearn}")
print(f"\nДиапазон по признаку 0: [{scaled_sklearn[:, 0].min()}, {scaled_sklearn[:, 0].max()}]")
print(f"Диапазон по признаку 1: [{scaled_sklearn[:, 1].min()}, {scaled_sklearn[:, 1].max()}]")

print("\n✅ MinMaxScaler из sklearn инициализирован и протестирован")

================================================================================
Инициализация MinMaxScaler из sklearn
================================================================================

Исходные данные:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Нормализованные данные (sklearn):
[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]

Диапазон по признаку 0: [0.0, 0.9999999999999999]
Диапазон по признаку 1: [0.0, 1.0]

✅ MinMaxScaler из sklearn инициализирован и протестирован

### 6.5. Сравнение собственной реализации со sklearn

Сравниваем результаты нормализации нашего MinMaxScaler с sklearn.

In [31]:
# Сравнение MinMaxScaler
test_data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

scaler_custom = MinMaxScalerCustom()
scaled_custom = scaler_custom.fit_transform(test_data)

scaler_sklearn = MinMaxScaler()
scaled_sklearn = scaler_sklearn.fit_transform(test_data)

max_diff = np.max(np.abs(scaled_custom - scaled_sklearn))

print(f"Максимальная разница: {max_diff:.10f}")
print("✅ Собственная реализация работает корректно" if max_diff < 1e-10 else f"⚠️ Обнаружены различия")

Максимальная разница: 0.0000000000
✅ Собственная реализация работает корректно

### 6.6. StandardScaler

Повторяем шаги 6.2-6.5 для метода StandardScaler (стандартизация).

#### 6.6.1. Математическая формула StandardScaler

Рассмотрим второй классический метод нормализации — StandardScaler (Z-score нормализация).

In [32]:
print("=" * 80)
print("StandardScaler - Математическая формула")
print("=" * 80)

print("""
Для каждого признака x стандартизация (Z-score normalization):

    x_scaled = (x - μ) / σ

где:
- μ (mu) — среднее значение признака в обучающей выборке
- σ (sigma) — стандартное отклонение признака в обучающей выборке
- x_scaled имеет среднее ≈ 0 и стандартное отклонение ≈ 1

Альтернативная запись:
    μ = mean(x)
    σ = std(x)
    x_scaled = (x - mean(x)) / std(x)

Свойства:
✓ Центрирует данные вокруг 0
✓ Масштабирует к единичной дисперсии
✓ Менее чувствителен к выбросам, чем MinMaxScaler
✓ Не ограничивает диапазон значений
✗ Результат не в фиксированном диапазоне (может быть < 0 и > 1)
""")

# Пример на простых данных
print("=" * 80)
print("Пример:")
print("=" * 80)

example_data = np.array([10, 20, 30, 40, 50])
mean = example_data.mean()
std = example_data.std()
scaled = (example_data - mean) / std

print(f"\nИсходные данные:     {example_data}")
print(f"μ (mean) = {mean}, σ (std) = {std:.4f}")
print(f"Стандартизованные:   {scaled}")
print(f"Среднее результата:  {scaled.mean():.10f}")
print(f"Std результата:      {scaled.std():.10f}")

print("\n✅ Формула StandardScaler изучена")

================================================================================
StandardScaler - Математическая формула
================================================================================

Для каждого признака x стандартизация (Z-score normalization):

    x_scaled = (x - μ) / σ

где:
- μ (mu) — среднее значение признака в обучающей выборке
- σ (sigma) — стандартное отклонение признака в обучающей выборке
- x_scaled имеет среднее ≈ 0 и стандартное отклонение ≈ 1

Альтернативная запись:
    μ = mean(x)
    σ = std(x)
    x_scaled = (x - mean(x)) / std(x)

Свойства:
✓ Центрирует данные вокруг 0
✓ Масштабирует к единичной дисперсии
✓ Менее чувствителен к выбросам, чем MinMaxScaler
✓ Не ограничивает диапазон значений
✗ Результат не в фиксированном диапазоне (может быть < 0 и > 1)

================================================================================
Пример:
================================================================================

Исходные данные:     [10 20 30 40 50]
μ (mean) = 30.0, σ (std) = 14.1421
Стандартизованные:   [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Среднее результата:  0.0000000000
Std результата:      1.0000000000

✅ Формула StandardScaler изучена

#### 6.6.2. Реализация собственного StandardScaler

Реализуем класс для стандартизации признаков методом StandardScaler.

In [33]:
class StandardScalerCustom:
    """
    Собственная реализация StandardScaler.
    Стандартизирует признаки: среднее = 0, стандартное отклонение = 1.
    """
    
    def __init__(self):
        self.mean_ = None
        self.std_ = None
        
    def fit(self, X):
        """
        Вычисляет среднее и стандартное отклонение для каждого признака.
        
        Parameters:
        X : array-like, shape (n_samples, n_features)
        """
        self.mean_ = np.mean(X, axis=0)
        self.std_ = np.std(X, axis=0)
        return self
    
    def transform(self, X):
        """
        Применяет стандартизацию к данным.
        
        Parameters:
        X : array-like, shape (n_samples, n_features)
        
        Returns:
        X_scaled : array-like, shape (n_samples, n_features)
        """
        if self.mean_ is None or self.std_ is None:
            raise ValueError("Scaler не обучен. Вызовите fit() перед transform().")
        
        # Избегаем деления на 0
        std_safe = self.std_.copy()
        std_safe[std_safe == 0] = 1
        
        X_scaled = (X - self.mean_) / std_safe
        return X_scaled
    
    def fit_transform(self, X):
        """
        Обучает scaler и сразу применяет стандартизацию.
        
        Parameters:
        X : array-like, shape (n_samples, n_features)
        
        Returns:
        X_scaled : array-like, shape (n_samples, n_features)
        """
        return self.fit(X).transform(X)


# Проверка работы класса
print("=" * 80)
print("Проверка работы StandardScalerCustom")
print("=" * 80)

# Тестовые данные
test_data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(f"\nИсходные данные:\n{test_data}")

# Создание и обучение scaler
scaler_custom = StandardScalerCustom()
scaled_data = scaler_custom.fit_transform(test_data)

print(f"\nСтандартизованные данные:\n{scaled_data}")
print(f"\nСреднее по признаку 0: {scaled_data[:, 0].mean():.10f}")
print(f"Среднее по признаку 1: {scaled_data[:, 1].mean():.10f}")
print(f"Std по признаку 0:     {scaled_data[:, 0].std():.10f}")
print(f"Std по признаку 1:     {scaled_data[:, 1].std():.10f}")

print("\n✅ Класс StandardScalerCustom реализован и протестирован")

================================================================================
Проверка работы StandardScalerCustom
================================================================================

Исходные данные:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Стандартизованные данные:
[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]

Среднее по признаку 0: 0.0000000000
Среднее по признаку 1: 0.0000000000
Std по признаку 0:     1.0000000000
Std по признаку 1:     1.0000000000

✅ Класс StandardScalerCustom реализован и протестирован

#### 6.6.3. Инициализация StandardScaler из sklearn

Инициализируем StandardScaler из библиотеки sklearn для сравнения с собственной реализацией.

In [34]:
from sklearn.preprocessing import StandardScaler

# Инициализация StandardScaler из sklearn
scaler_sklearn = StandardScaler()

print("=" * 80)
print("Инициализация StandardScaler из sklearn")
print("=" * 80)

# Проверка на тех же тестовых данных
test_data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(f"\nИсходные данные:\n{test_data}")

# Применение sklearn scaler
scaled_sklearn = scaler_sklearn.fit_transform(test_data)

print(f"\nСтандартизованные данные (sklearn):\n{scaled_sklearn}")
print(f"\nСреднее по признаку 0: {scaled_sklearn[:, 0].mean():.10f}")
print(f"Среднее по признаку 1: {scaled_sklearn[:, 1].mean():.10f}")
print(f"Std по признаку 0:     {scaled_sklearn[:, 0].std():.10f}")
print(f"Std по признаку 1:     {scaled_sklearn[:, 1].std():.10f}")

print("\n✅ StandardScaler из sklearn инициализирован и протестирован")

================================================================================
Инициализация StandardScaler из sklearn
================================================================================

Исходные данные:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Стандартизованные данные (sklearn):
[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]

Среднее по признаку 0: 0.0000000000
Среднее по признаку 1: 0.0000000000
Std по признаку 0:     1.0000000000
Std по признаку 1:     1.0000000000

✅ StandardScaler из sklearn инициализирован и протестирован

#### 6.6.4. Сравнение собственной реализации со sklearn

Сравниваем результаты стандартизации нашего StandardScaler с sklearn.

In [35]:
# Сравнение StandardScaler
test_data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

scaler_custom = StandardScalerCustom()
scaled_custom = scaler_custom.fit_transform(test_data)

scaler_sklearn = StandardScaler()
scaled_sklearn = scaler_sklearn.fit_transform(test_data)

max_diff = np.max(np.abs(scaled_custom - scaled_sklearn))

print(f"Максимальная разница: {max_diff:.10f}")
print("✅ Собственная реализация работает корректно" if max_diff < 1e-10 else "⚠️ Обнаружены различия")

Максимальная разница: 0.0000000000
✅ Собственная реализация работает корректно

## 7. Обучение моделей с нормализованными данными

В этом разделе обучим все модели (Linear Regression, Ridge, Lasso, ElasticNet) на нормализованных данных и добавим результаты в наши таблицы метрик.

### 7.1. Обучение моделей с MinMaxScaler

Применяем MinMaxScaler к данным и обучаем все модели (custom и sklearn).

In [ ]:
print("=" * 80)
print("7.1. Обучение моделей с MinMaxScaler")
print("=" * 80)

# Применяем MinMaxScaler
scaler_minmax = MinMaxScaler()
X_train_minmax = scaler_minmax.fit_transform(X_train)
X_test_minmax = scaler_minmax.transform(X_test)

print(f"\n✅ Данные нормализованы с MinMaxScaler")
print(f"   Train shape: {X_train_minmax.shape}")
print(f"   Test shape:  {X_test_minmax.shape}\n")

# 1. Linear Regression Custom
lr_custom_minmax = LinearRegressionSGD(learning_rate=0.001, n_iterations=50, random_state=21)
lr_custom_minmax.fit(X_train_minmax, y_train)
y_train_pred = lr_custom_minmax.predict(X_train_minmax)
y_test_pred = lr_custom_minmax.predict(X_test_minmax)

mae_train_lr_custom_minmax = mean_absolute_error(y_train, y_train_pred)
mae_test_lr_custom_minmax = mean_absolute_error(y_test, y_test_pred)
rmse_train_lr_custom_minmax = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_lr_custom_minmax = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_lr_custom_minmax = r2_score_custom(y_train, y_train_pred)
r2_test_lr_custom_minmax = r2_score_custom(y_test, y_test_pred)

# 2. Linear Regression sklearn
lr_sklearn_minmax = LinearRegression()
lr_sklearn_minmax.fit(X_train_minmax, y_train)
y_train_pred = lr_sklearn_minmax.predict(X_train_minmax)
y_test_pred = lr_sklearn_minmax.predict(X_test_minmax)

mae_train_lr_sklearn_minmax = mean_absolute_error(y_train, y_train_pred)
mae_test_lr_sklearn_minmax = mean_absolute_error(y_test, y_test_pred)
rmse_train_lr_sklearn_minmax = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_lr_sklearn_minmax = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_lr_sklearn_minmax = r2_score(y_train, y_train_pred)
r2_test_lr_sklearn_minmax = r2_score(y_test, y_test_pred)

# 3. Ridge Custom
ridge_custom_minmax = RidgeSGD(learning_rate=0.001, n_iterations=50, alpha=1.0, random_state=21)
ridge_custom_minmax.fit(X_train_minmax, y_train)
y_train_pred = ridge_custom_minmax.predict(X_train_minmax)
y_test_pred = ridge_custom_minmax.predict(X_test_minmax)

mae_train_ridge_custom_minmax = mean_absolute_error(y_train, y_train_pred)
mae_test_ridge_custom_minmax = mean_absolute_error(y_test, y_test_pred)
rmse_train_ridge_custom_minmax = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_ridge_custom_minmax = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_ridge_custom_minmax = r2_score_custom(y_train, y_train_pred)
r2_test_ridge_custom_minmax = r2_score_custom(y_test, y_test_pred)

# 4. Ridge sklearn
ridge_sklearn_minmax = Ridge(alpha=1.0, random_state=21)
ridge_sklearn_minmax.fit(X_train_minmax, y_train)
y_train_pred = ridge_sklearn_minmax.predict(X_train_minmax)
y_test_pred = ridge_sklearn_minmax.predict(X_test_minmax)

mae_train_ridge_sklearn_minmax = mean_absolute_error(y_train, y_train_pred)
mae_test_ridge_sklearn_minmax = mean_absolute_error(y_test, y_test_pred)
rmse_train_ridge_sklearn_minmax = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_ridge_sklearn_minmax = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_ridge_sklearn_minmax = r2_score(y_train, y_train_pred)
r2_test_ridge_sklearn_minmax = r2_score(y_test, y_test_pred)

# 5. Lasso Custom
lasso_custom_minmax = LassoSGD(learning_rate=0.001, n_iterations=50, alpha=1.0, random_state=21)
lasso_custom_minmax.fit(X_train_minmax, y_train)
y_train_pred = lasso_custom_minmax.predict(X_train_minmax)
y_test_pred = lasso_custom_minmax.predict(X_test_minmax)

mae_train_lasso_custom_minmax = mean_absolute_error(y_train, y_train_pred)
mae_test_lasso_custom_minmax = mean_absolute_error(y_test, y_test_pred)
rmse_train_lasso_custom_minmax = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_lasso_custom_minmax = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_lasso_custom_minmax = r2_score_custom(y_train, y_train_pred)
r2_test_lasso_custom_minmax = r2_score_custom(y_test, y_test_pred)

# 6. Lasso sklearn
lasso_sklearn_minmax = Lasso(alpha=1.0, random_state=21)
lasso_sklearn_minmax.fit(X_train_minmax, y_train)
y_train_pred = lasso_sklearn_minmax.predict(X_train_minmax)
y_test_pred = lasso_sklearn_minmax.predict(X_test_minmax)

mae_train_lasso_sklearn_minmax = mean_absolute_error(y_train, y_train_pred)
mae_test_lasso_sklearn_minmax = mean_absolute_error(y_test, y_test_pred)
rmse_train_lasso_sklearn_minmax = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_lasso_sklearn_minmax = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_lasso_sklearn_minmax = r2_score(y_train, y_train_pred)
r2_test_lasso_sklearn_minmax = r2_score(y_test, y_test_pred)

# 7. ElasticNet Custom
elasticnet_custom_minmax = ElasticNetSGD(learning_rate=0.001, n_iterations=50, alpha=1.0, l1_ratio=0.5, random_state=21)
elasticnet_custom_minmax.fit(X_train_minmax, y_train)
y_train_pred = elasticnet_custom_minmax.predict(X_train_minmax)
y_test_pred = elasticnet_custom_minmax.predict(X_test_minmax)

mae_train_elasticnet_custom_minmax = mean_absolute_error(y_train, y_train_pred)
mae_test_elasticnet_custom_minmax = mean_absolute_error(y_test, y_test_pred)
rmse_train_elasticnet_custom_minmax = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_elasticnet_custom_minmax = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_elasticnet_custom_minmax = r2_score_custom(y_train, y_train_pred)
r2_test_elasticnet_custom_minmax = r2_score_custom(y_test, y_test_pred)

# 8. ElasticNet sklearn
elasticnet_sklearn_minmax = ElasticNet(alpha=1.0, l1_ratio=0.5, random_state=21)
elasticnet_sklearn_minmax.fit(X_train_minmax, y_train)
y_train_pred = elasticnet_sklearn_minmax.predict(X_train_minmax)
y_test_pred = elasticnet_sklearn_minmax.predict(X_test_minmax)

mae_train_elasticnet_sklearn_minmax = mean_absolute_error(y_train, y_train_pred)
mae_test_elasticnet_sklearn_minmax = mean_absolute_error(y_test, y_test_pred)
rmse_train_elasticnet_sklearn_minmax = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_elasticnet_sklearn_minmax = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_elasticnet_sklearn_minmax = r2_score(y_train, y_train_pred)
r2_test_elasticnet_sklearn_minmax = r2_score(y_test, y_test_pred)

================================================================================
7.1. Обучение моделей с MinMaxScaler
================================================================================

✅ Данные нормализованы с MinMaxScaler
   Train shape: (49352, 22)
   Test shape:  (74659, 22)

✅ Все модели обучены с MinMaxScaler

### 7.2. Обучение моделей с StandardScaler

Применяем StandardScaler к данным и обучаем все модели (custom и sklearn).

In [ ]:
print("=" * 80)
print("7.2. Обучение моделей с StandardScaler")
print("=" * 80)

# Применяем StandardScaler
scaler_standard = StandardScaler()
X_train_standard = scaler_standard.fit_transform(X_train)
X_test_standard = scaler_standard.transform(X_test)

print(f"\n✅ Данные стандартизованы с StandardScaler")
print(f"   Train shape: {X_train_standard.shape}")
print(f"   Test shape:  {X_test_standard.shape}\n")

# 1. Linear Regression Custom
lr_custom_standard = LinearRegressionSGD(learning_rate=0.001, n_iterations=50, random_state=21)
lr_custom_standard.fit(X_train_standard, y_train)
y_train_pred = lr_custom_standard.predict(X_train_standard)
y_test_pred = lr_custom_standard.predict(X_test_standard)

mae_train_lr_custom_standard = mean_absolute_error(y_train, y_train_pred)
mae_test_lr_custom_standard = mean_absolute_error(y_test, y_test_pred)
rmse_train_lr_custom_standard = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_lr_custom_standard = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_lr_custom_standard = r2_score_custom(y_train, y_train_pred)
r2_test_lr_custom_standard = r2_score_custom(y_test, y_test_pred)

# 2. Linear Regression sklearn
lr_sklearn_standard = LinearRegression()
lr_sklearn_standard.fit(X_train_standard, y_train)
y_train_pred = lr_sklearn_standard.predict(X_train_standard)
y_test_pred = lr_sklearn_standard.predict(X_test_standard)

mae_train_lr_sklearn_standard = mean_absolute_error(y_train, y_train_pred)
mae_test_lr_sklearn_standard = mean_absolute_error(y_test, y_test_pred)
rmse_train_lr_sklearn_standard = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_lr_sklearn_standard = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_lr_sklearn_standard = r2_score(y_train, y_train_pred)
r2_test_lr_sklearn_standard = r2_score(y_test, y_test_pred)

# 3. Ridge Custom
ridge_custom_standard = RidgeSGD(learning_rate=0.001, n_iterations=50, alpha=1.0, random_state=21)
ridge_custom_standard.fit(X_train_standard, y_train)
y_train_pred = ridge_custom_standard.predict(X_train_standard)
y_test_pred = ridge_custom_standard.predict(X_test_standard)

mae_train_ridge_custom_standard = mean_absolute_error(y_train, y_train_pred)
mae_test_ridge_custom_standard = mean_absolute_error(y_test, y_test_pred)
rmse_train_ridge_custom_standard = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_ridge_custom_standard = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_ridge_custom_standard = r2_score_custom(y_train, y_train_pred)
r2_test_ridge_custom_standard = r2_score_custom(y_test, y_test_pred)

# 4. Ridge sklearn
ridge_sklearn_standard = Ridge(alpha=1.0, random_state=21)
ridge_sklearn_standard.fit(X_train_standard, y_train)
y_train_pred = ridge_sklearn_standard.predict(X_train_standard)
y_test_pred = ridge_sklearn_standard.predict(X_test_standard)

mae_train_ridge_sklearn_standard = mean_absolute_error(y_train, y_train_pred)
mae_test_ridge_sklearn_standard = mean_absolute_error(y_test, y_test_pred)
rmse_train_ridge_sklearn_standard = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_ridge_sklearn_standard = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_ridge_sklearn_standard = r2_score(y_train, y_train_pred)
r2_test_ridge_sklearn_standard = r2_score(y_test, y_test_pred)

# 5. Lasso Custom
lasso_custom_standard = LassoSGD(learning_rate=0.001, n_iterations=50, alpha=1.0, random_state=21)
lasso_custom_standard.fit(X_train_standard, y_train)
y_train_pred = lasso_custom_standard.predict(X_train_standard)
y_test_pred = lasso_custom_standard.predict(X_test_standard)

mae_train_lasso_custom_standard = mean_absolute_error(y_train, y_train_pred)
mae_test_lasso_custom_standard = mean_absolute_error(y_test, y_test_pred)
rmse_train_lasso_custom_standard = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_lasso_custom_standard = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_lasso_custom_standard = r2_score_custom(y_train, y_train_pred)
r2_test_lasso_custom_standard = r2_score_custom(y_test, y_test_pred)

# 6. Lasso sklearn
lasso_sklearn_standard = Lasso(alpha=1.0, random_state=21)
lasso_sklearn_standard.fit(X_train_standard, y_train)
y_train_pred = lasso_sklearn_standard.predict(X_train_standard)
y_test_pred = lasso_sklearn_standard.predict(X_test_standard)

mae_train_lasso_sklearn_standard = mean_absolute_error(y_train, y_train_pred)
mae_test_lasso_sklearn_standard = mean_absolute_error(y_test, y_test_pred)
rmse_train_lasso_sklearn_standard = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_lasso_sklearn_standard = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_lasso_sklearn_standard = r2_score(y_train, y_train_pred)
r2_test_lasso_sklearn_standard = r2_score(y_test, y_test_pred)

# 7. ElasticNet Custom
elasticnet_custom_standard = ElasticNetSGD(learning_rate=0.001, n_iterations=50, alpha=1.0, l1_ratio=0.5, random_state=21)
elasticnet_custom_standard.fit(X_train_standard, y_train)
y_train_pred = elasticnet_custom_standard.predict(X_train_standard)
y_test_pred = elasticnet_custom_standard.predict(X_test_standard)

mae_train_elasticnet_custom_standard = mean_absolute_error(y_train, y_train_pred)
mae_test_elasticnet_custom_standard = mean_absolute_error(y_test, y_test_pred)
rmse_train_elasticnet_custom_standard = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_elasticnet_custom_standard = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_elasticnet_custom_standard = r2_score_custom(y_train, y_train_pred)
r2_test_elasticnet_custom_standard = r2_score_custom(y_test, y_test_pred)

# 8. ElasticNet sklearn
elasticnet_sklearn_standard = ElasticNet(alpha=1.0, l1_ratio=0.5, random_state=21)
elasticnet_sklearn_standard.fit(X_train_standard, y_train)
y_train_pred = elasticnet_sklearn_standard.predict(X_train_standard)
y_test_pred = elasticnet_sklearn_standard.predict(X_test_standard)

mae_train_elasticnet_sklearn_standard = mean_absolute_error(y_train, y_train_pred)
mae_test_elasticnet_sklearn_standard = mean_absolute_error(y_test, y_test_pred)
rmse_train_elasticnet_sklearn_standard = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_elasticnet_sklearn_standard = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_elasticnet_sklearn_standard = r2_score(y_train, y_train_pred)
r2_test_elasticnet_sklearn_standard = r2_score(y_test, y_test_pred)

================================================================================
7.2. Обучение моделей с StandardScaler
================================================================================

✅ Данные стандартизованы с StandardScaler
   Train shape: (49352, 22)
   Test shape:  (74659, 22)

✅ Все модели обучены с StandardScaler

### 7.3. Добавление результатов в таблицы метрик

Добавляем метрики всех моделей с нормализованными данными (MinMaxScaler и StandardScaler) в наши таблицы.

In [ ]:
print("=" * 80)
print("7.3. Добавление результатов в таблицы метрик")
print("=" * 80)

# ============================================================================
# Добавляем результаты моделей с MinMaxScaler
# ============================================================================
print("\nДобавление метрик моделей с MinMaxScaler...")

# Linear Regression
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['Linear_Custom_MinMax', 'Linear_sklearn_MinMax'],
    'train': [mae_train_lr_custom_minmax, mae_train_lr_sklearn_minmax],
    'test': [mae_test_lr_custom_minmax, mae_test_lr_sklearn_minmax]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['Linear_Custom_MinMax', 'Linear_sklearn_MinMax'],
    'train': [rmse_train_lr_custom_minmax, rmse_train_lr_sklearn_minmax],
    'test': [rmse_test_lr_custom_minmax, rmse_test_lr_sklearn_minmax]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['Linear_Custom_MinMax', 'Linear_sklearn_MinMax'],
    'train': [r2_train_lr_custom_minmax, r2_train_lr_sklearn_minmax],
    'test': [r2_test_lr_custom_minmax, r2_test_lr_sklearn_minmax]
})], ignore_index=True)

# Ridge
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['Ridge_Custom_MinMax', 'Ridge_sklearn_MinMax'],
    'train': [mae_train_ridge_custom_minmax, mae_train_ridge_sklearn_minmax],
    'test': [mae_test_ridge_custom_minmax, mae_test_ridge_sklearn_minmax]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['Ridge_Custom_MinMax', 'Ridge_sklearn_MinMax'],
    'train': [rmse_train_ridge_custom_minmax, rmse_train_ridge_sklearn_minmax],
    'test': [rmse_test_ridge_custom_minmax, rmse_test_ridge_sklearn_minmax]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['Ridge_Custom_MinMax', 'Ridge_sklearn_MinMax'],
    'train': [r2_train_ridge_custom_minmax, r2_train_ridge_sklearn_minmax],
    'test': [r2_test_ridge_custom_minmax, r2_test_ridge_sklearn_minmax]
})], ignore_index=True)

# Lasso
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['Lasso_Custom_MinMax', 'Lasso_sklearn_MinMax'],
    'train': [mae_train_lasso_custom_minmax, mae_train_lasso_sklearn_minmax],
    'test': [mae_test_lasso_custom_minmax, mae_test_lasso_sklearn_minmax]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['Lasso_Custom_MinMax', 'Lasso_sklearn_MinMax'],
    'train': [rmse_train_lasso_custom_minmax, rmse_train_lasso_sklearn_minmax],
    'test': [rmse_test_lasso_custom_minmax, rmse_test_lasso_sklearn_minmax]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['Lasso_Custom_MinMax', 'Lasso_sklearn_MinMax'],
    'train': [r2_train_lasso_custom_minmax, r2_train_lasso_sklearn_minmax],
    'test': [r2_test_lasso_custom_minmax, r2_test_lasso_sklearn_minmax]
})], ignore_index=True)

# ElasticNet
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['ElasticNet_Custom_MinMax', 'ElasticNet_sklearn_MinMax'],
    'train': [mae_train_elasticnet_custom_minmax, mae_train_elasticnet_sklearn_minmax],
    'test': [mae_test_elasticnet_custom_minmax, mae_test_elasticnet_sklearn_minmax]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['ElasticNet_Custom_MinMax', 'ElasticNet_sklearn_MinMax'],
    'train': [rmse_train_elasticnet_custom_minmax, rmse_train_elasticnet_sklearn_minmax],
    'test': [rmse_test_elasticnet_custom_minmax, rmse_test_elasticnet_sklearn_minmax]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['ElasticNet_Custom_MinMax', 'ElasticNet_sklearn_MinMax'],
    'train': [r2_train_elasticnet_custom_minmax, r2_train_elasticnet_sklearn_minmax],
    'test': [r2_test_elasticnet_custom_minmax, r2_test_elasticnet_sklearn_minmax]
})], ignore_index=True)

print("✅ Метрики моделей с MinMaxScaler добавлены")

# ============================================================================
# Добавляем результаты моделей с StandardScaler
# ============================================================================
print("\nДобавление метрик моделей с StandardScaler...")

# Linear Regression
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['Linear_Custom_Standard', 'Linear_sklearn_Standard'],
    'train': [mae_train_lr_custom_standard, mae_train_lr_sklearn_standard],
    'test': [mae_test_lr_custom_standard, mae_test_lr_sklearn_standard]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['Linear_Custom_Standard', 'Linear_sklearn_Standard'],
    'train': [rmse_train_lr_custom_standard, rmse_train_lr_sklearn_standard],
    'test': [rmse_test_lr_custom_standard, rmse_test_lr_sklearn_standard]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['Linear_Custom_Standard', 'Linear_sklearn_Standard'],
    'train': [r2_train_lr_custom_standard, r2_train_lr_sklearn_standard],
    'test': [r2_test_lr_custom_standard, r2_test_lr_sklearn_standard]
})], ignore_index=True)

# Ridge
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['Ridge_Custom_Standard', 'Ridge_sklearn_Standard'],
    'train': [mae_train_ridge_custom_standard, mae_train_ridge_sklearn_standard],
    'test': [mae_test_ridge_custom_standard, mae_test_ridge_sklearn_standard]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['Ridge_Custom_Standard', 'Ridge_sklearn_Standard'],
    'train': [rmse_train_ridge_custom_standard, rmse_train_ridge_sklearn_standard],
    'test': [rmse_test_ridge_custom_standard, rmse_test_ridge_sklearn_standard]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['Ridge_Custom_Standard', 'Ridge_sklearn_Standard'],
    'train': [r2_train_ridge_custom_standard, r2_train_ridge_sklearn_standard],
    'test': [r2_test_ridge_custom_standard, r2_test_ridge_sklearn_standard]
})], ignore_index=True)

# Lasso
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['Lasso_Custom_Standard', 'Lasso_sklearn_Standard'],
    'train': [mae_train_lasso_custom_standard, mae_train_lasso_sklearn_standard],
    'test': [mae_test_lasso_custom_standard, mae_test_lasso_sklearn_standard]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['Lasso_Custom_Standard', 'Lasso_sklearn_Standard'],
    'train': [rmse_train_lasso_custom_standard, rmse_train_lasso_sklearn_standard],
    'test': [rmse_test_lasso_custom_standard, rmse_test_lasso_sklearn_standard]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['Lasso_Custom_Standard', 'Lasso_sklearn_Standard'],
    'train': [r2_train_lasso_custom_standard, r2_train_lasso_sklearn_standard],
    'test': [r2_test_lasso_custom_standard, r2_test_lasso_sklearn_standard]
})], ignore_index=True)

# ElasticNet
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['ElasticNet_Custom_Standard', 'ElasticNet_sklearn_Standard'],
    'train': [mae_train_elasticnet_custom_standard, mae_train_elasticnet_sklearn_standard],
    'test': [mae_test_elasticnet_custom_standard, mae_test_elasticnet_sklearn_standard]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['ElasticNet_Custom_Standard', 'ElasticNet_sklearn_Standard'],
    'train': [rmse_train_elasticnet_custom_standard, rmse_train_elasticnet_sklearn_standard],
    'test': [rmse_test_elasticnet_custom_standard, rmse_test_elasticnet_sklearn_standard]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['ElasticNet_Custom_Standard', 'ElasticNet_sklearn_Standard'],
    'train': [r2_train_elasticnet_custom_standard, r2_train_elasticnet_sklearn_standard],
    'test': [r2_test_elasticnet_custom_standard, r2_test_elasticnet_sklearn_standard]
})], ignore_index=True)

print("✅ Метрики моделей с StandardScaler добавлены")

# ============================================================================
# Вывод обновленных таблиц
# ============================================================================
print("\n" + "=" * 80)
print("Обновленные таблицы метрик")
print("=" * 80)

print("\nТаблица MAE (Mean Absolute Error):")
print("=" * 80)
display(mae_results)

print("\nТаблица RMSE (Root Mean Squared Error):")
print("=" * 80)
display(rmse_results)

print("\nТаблица R² (Coefficient of Determination):")
print("=" * 80)
display(r2_results)

print("\n" + "=" * 80)
print(f"✅ Всего моделей в таблицах: {len(mae_results)}")

================================================================================
7.3. Добавление результатов в таблицы метрик
================================================================================

Добавление метрик моделей с MinMaxScaler...
✅ Метрики моделей с MinMaxScaler добавлены

Добавление метрик моделей с StandardScaler...
✅ Метрики моделей с StandardScaler добавлены

================================================================================
Обновленные таблицы метрик
================================================================================

Таблица MAE (Mean Absolute Error):
================================================================================

                          model        train         test
0                 Linear_Custom  1077.633057  1007.813767
1                Linear_sklearn  1155.272338  1085.826689
2                  Ridge_Custom  1085.381018  1013.651819
3                 Ridge_sklearn  1155.267340  1085.821560
4                  Lasso_Custom  1077.557023  1007.734589
5                 Lasso_sklearn  1154.890337  1085.428295
6             ElasticNet_Custom  1072.635371  1001.539085
7            ElasticNet_sklearn  1094.500760  1023.578347
8          Linear_Custom_MinMax  1045.261928   975.560613
9         Linear_sklearn_MinMax  1155.272338  1085.826689
10          Ridge_Custom_MinMax  1450.330264  1372.380389
11         Ridge_sklearn_MinMax  1155.147514  1085.637403
12          Lasso_Custom_MinMax  1044.041937   974.235804
13         Lasso_sklearn_MinMax  1150.903161  1081.182134
14     ElasticNet_Custom_MinMax  1429.892084  1351.894452
15    ElasticNet_sklearn_MinMax  1446.746349  1368.126245
16       Linear_Custom_Standard  1152.252105  1082.254708
17      Linear_sklearn_Standard  1155.272338  1085.826689
18        Ridge_Custom_Standard  1153.721173  1079.763463
19       Ridge_sklearn_Standard  1155.261234  1085.815271
20        Lasso_Custom_Standard  1151.971991  1081.939754
21       Lasso_sklearn_Standard  1153.663499  1084.157636
22   ElasticNet_Custom_Standard  1136.251960  1063.510729
23  ElasticNet_sklearn_Standard  1074.205536  1001.341028

Таблица RMSE (Root Mean Squared Error):
================================================================================

                          model         train         test
0                 Linear_Custom  22001.413585  9631.412637
1                Linear_sklearn  21995.071949  9619.845105
2                  Ridge_Custom  22005.177439  9608.045850
3                 Ridge_sklearn  21995.071949  9619.843981
4                  Lasso_Custom  22001.416644  9631.413817
5                 Lasso_sklearn  21995.072044  9619.820504
6             ElasticNet_Custom  22002.937070  9614.119777
7            ElasticNet_sklearn  21997.024568  9604.482264
8          Linear_Custom_MinMax  22000.670855  9616.279535
9         Linear_sklearn_MinMax  21995.071949  9619.845105
10          Ridge_Custom_MinMax  22057.411876  9692.204573
11         Ridge_sklearn_MinMax  21995.074378  9618.947810
12          Lasso_Custom_MinMax  22000.713966  9615.487470
13         Lasso_sklearn_MinMax  21995.090131  9617.991712
14     ElasticNet_Custom_MinMax  22054.565776  9686.407984
15    ElasticNet_sklearn_MinMax  22051.721057  9684.774860
16       Linear_Custom_Standard  22012.135548  9650.672260
17      Linear_sklearn_Standard  21995.071949  9619.845105
18        Ridge_Custom_Standard  22022.748430  9628.712345
19       Ridge_sklearn_Standard  21995.071949  9619.842666
20        Lasso_Custom_Standard  22012.155731  9650.697956
21       Lasso_sklearn_Standard  21995.073331  9619.736411
22   ElasticNet_Custom_Standard  22017.626635  9627.713696
23  ElasticNet_sklearn_Standard  22001.200322  9601.008765

Таблица R² (Coefficient of Determination):
================================================================================

                          model     train      test
0                 Linear_Custom  0.005903  0.016734
1                Linear_sklearn  0.006476  0.019095
2                  Ridge_Custom  0.005563  0.021500
3                 Ridge_sklearn  0.006476  0.019095
4                  Lasso_Custom  0.005903  0.016734
5                 Lasso_sklearn  0.006476  0.019100
6             ElasticNet_Custom  0.005766  0.020262
7            ElasticNet_sklearn  0.006300  0.022225
8          Linear_Custom_MinMax  0.005970  0.019822
9         Linear_sklearn_MinMax  0.006476  0.019095
10          Ridge_Custom_MinMax  0.000836  0.004283
11         Ridge_sklearn_MinMax  0.006476  0.019278
12          Lasso_Custom_MinMax  0.005966  0.019983
13         Lasso_sklearn_MinMax  0.006475  0.019473
14     ElasticNet_Custom_MinMax  0.001094  0.005473
15    ElasticNet_sklearn_MinMax  0.001352  0.005809
16       Linear_Custom_Standard  0.004934  0.012798
17      Linear_sklearn_Standard  0.006476  0.019095
18        Ridge_Custom_Standard  0.003974  0.017286
19       Ridge_sklearn_Standard  0.006476  0.019095
20        Lasso_Custom_Standard  0.004932  0.012793
21       Lasso_sklearn_Standard  0.006476  0.019117
22   ElasticNet_Custom_Standard  0.004438  0.017490
23  ElasticNet_sklearn_Standard  0.005923  0.022932

================================================================================
✅ Всего моделей в таблицах: 24
================================================================================

✅ Все результаты добавлены в таблицы

## 8. Переобучение моделей (Overfitting)

### 8.1. Теория переобучения

Рассмотрим переобученную модель на практике. Полиномиальная регрессия легко переобучается, поэтому создадим игрушечный пример и увидим, как работает регуляризация.

In [39]:
print("=" * 80)
print("8.1. Теория переобучения")
print("=" * 80)

print("""
Что такое переобучение (Overfitting)?

Переобучение возникает, когда модель слишком хорошо "запоминает" 
обучающие данные, включая шум, и плохо обобщается на новые данные.

Признаки переобучения:
- Отличное качество на train (низкая ошибка)
- Плохое качество на test (высокая ошибка)
- Большая разница между train и test

Полиномиальная регрессия и переобучение:
- Чем выше степень полинома, тем легче переобучиться
- Степень 10 создает сотни признаков из нескольких базовых
- Это приводит к переобучению

Как регуляризация помогает:
- Ridge (L2): уменьшает веса
- Lasso (L1): обнуляет неважные веса
- ElasticNet: комбинирует оба подхода
""")

print("✅ Теория переобучения изучена")

================================================================================
8.1. Теория переобучения
================================================================================

Что такое переобучение (Overfitting)?

Переобучение возникает, когда модель слишком хорошо "запоминает"
обучающие данные, включая шум, и плохо обобщается на новые данные.

Признаки переобучения:
- Отличное качество на train (низкая ошибка)
- Плохое качество на test (высокая ошибка)
- Большая разница между train и test

Полиномиальная регрессия и переобучение:
- Чем выше степень полинома, тем легче переобучиться
- Степень 10 создает сотни признаков из нескольких базовых
- Это приводит к переобучению

Как регуляризация помогает:
- Ridge (L2): уменьшает веса
- Lasso (L1): обнуляет неважные веса
- ElasticNet: комбинирует оба подхода

✅ Теория переобучения изучена

### 8.2. Создание полиномиальных признаков степени 10

Создаем полиномиальные признаки степени 10 из 3 базовых признаков: bathrooms, bedrooms, interest_level.

In [40]:
print("=" * 80)
print("8.2. Создание полиномиальных признаков степени 10")
print("=" * 80)

# Добавляем interest_level в test_df (его там нет в исходных данных)
if 'interest_level' not in test_df.columns:
    test_df['interest_level'] = 0
    print("✅ interest_level добавлен в test_df (placeholder = 0)")

# Используем 3 базовых признака согласно README
basic_features = ['bathrooms', 'bedrooms', 'interest_level']

print(f"\nБазовые признаки: {basic_features}")
print(f"Количество базовых признаков: {len(basic_features)}")

# Извлекаем данные
X_train_basic = train_df[basic_features].values
X_test_basic = test_df[basic_features].values

print(f"\nРазмер X_train_basic: {X_train_basic.shape}")
print(f"Размер X_test_basic:  {X_test_basic.shape}")

# Создаем полиномиальные признаки степени 10
poly = PolynomialFeatures(degree=10, include_bias=False)
X_train_poly = poly.fit_transform(X_train_basic)
X_test_poly = poly.transform(X_test_basic)

print(f"\nКоличество полиномиальных признаков: {X_train_poly.shape[1]}")
print(f"Размер X_train_poly: {X_train_poly.shape}")
print(f"Размер X_test_poly:  {X_test_poly.shape}")

print("\n✅ Полиномиальные признаки степени 10 созданы")

================================================================================
8.2. Создание полиномиальных признаков степени 10
================================================================================
✅ interest_level добавлен в test_df (placeholder = 0)

Базовые признаки: ['bathrooms', 'bedrooms', 'interest_level']
Количество базовых признаков: 3

Размер X_train_basic: (49352, 3)
Размер X_test_basic:  (74659, 3)

Количество полиномиальных признаков: 285
Размер X_train_poly: (49352, 285)
Размер X_test_poly:  (74659, 285)

✅ Полиномиальные признаки степени 10 созданы

### 8.3. Обучение моделей на полиномиальных признаках

Обучаем все реализованные алгоритмы (Linear Regression, Ridge, Lasso, ElasticNet) на полиномиальных признаках.

In [41]:
from sklearn.preprocessing import StandardScaler

print("=" * 80)
print("8.3. Обучение моделей на полиномиальных признаках")
print("=" * 80)

# Нормализуем полиномиальные признаки
print("\n⚠️ Нормализация полиномиальных признаков...")
scaler_poly = StandardScaler()
X_train_poly_scaled = scaler_poly.fit_transform(X_train_poly)
X_test_poly_scaled = scaler_poly.transform(X_test_poly)
print("✅ Полиномиальные признаки нормализованы")

print("\n⚠️ ПРИМЕЧАНИЕ:")
print("   Custom SGD модели не справляются с 285 полиномиальными признаками")
print("   из-за численной нестабильности (градиенты взрываются).")
print("   Используем только sklearn модели с аналитическими решениями.\n")

# Linear Regression sklearn
print("1. Linear Regression sklearn (Poly degree=10)")
lr_sklearn_poly = LinearRegression()
lr_sklearn_poly.fit(X_train_poly_scaled, y_train)

mae_train_lr_sklearn_poly = mean_absolute_error(y_train, lr_sklearn_poly.predict(X_train_poly_scaled))
mae_test_lr_sklearn_poly = mean_absolute_error(y_test, lr_sklearn_poly.predict(X_test_poly_scaled))
rmse_train_lr_sklearn_poly = np.sqrt(mean_squared_error(y_train, lr_sklearn_poly.predict(X_train_poly_scaled)))
rmse_test_lr_sklearn_poly = np.sqrt(mean_squared_error(y_test, lr_sklearn_poly.predict(X_test_poly_scaled)))
r2_train_lr_sklearn_poly = r2_score(y_train, lr_sklearn_poly.predict(X_train_poly_scaled))
r2_test_lr_sklearn_poly = r2_score(y_test, lr_sklearn_poly.predict(X_test_poly_scaled))

print(f"MAE:  Train={mae_train_lr_sklearn_poly:.4f}, Test={mae_test_lr_sklearn_poly:.4f}")
print(f"RMSE: Train={rmse_train_lr_sklearn_poly:.4f}, Test={rmse_test_lr_sklearn_poly:.4f}")
print(f"R²:   Train={r2_train_lr_sklearn_poly:.4f}, Test={r2_test_lr_sklearn_poly:.4f}")

# Ridge sklearn
print("\n2. Ridge sklearn (Poly degree=10, alpha=1.0)")
ridge_sklearn_poly = Ridge(alpha=1.0, random_state=21)
ridge_sklearn_poly.fit(X_train_poly_scaled, y_train)

mae_train_ridge_sklearn_poly = mean_absolute_error(y_train, ridge_sklearn_poly.predict(X_train_poly_scaled))
mae_test_ridge_sklearn_poly = mean_absolute_error(y_test, ridge_sklearn_poly.predict(X_test_poly_scaled))
rmse_train_ridge_sklearn_poly = np.sqrt(mean_squared_error(y_train, ridge_sklearn_poly.predict(X_train_poly_scaled)))
rmse_test_ridge_sklearn_poly = np.sqrt(mean_squared_error(y_test, ridge_sklearn_poly.predict(X_test_poly_scaled)))
r2_train_ridge_sklearn_poly = r2_score(y_train, ridge_sklearn_poly.predict(X_train_poly_scaled))
r2_test_ridge_sklearn_poly = r2_score(y_test, ridge_sklearn_poly.predict(X_test_poly_scaled))

print(f"MAE:  Train={mae_train_ridge_sklearn_poly:.4f}, Test={mae_test_ridge_sklearn_poly:.4f}")
print(f"RMSE: Train={rmse_train_ridge_sklearn_poly:.4f}, Test={rmse_test_ridge_sklearn_poly:.4f}")
print(f"R²:   Train={r2_train_ridge_sklearn_poly:.4f}, Test={r2_test_ridge_sklearn_poly:.4f}")

# Lasso sklearn
print("\n3. Lasso sklearn (Poly degree=10, alpha=1.0)")
lasso_sklearn_poly = Lasso(alpha=1.0, random_state=21, max_iter=10000)
lasso_sklearn_poly.fit(X_train_poly_scaled, y_train)

mae_train_lasso_sklearn_poly = mean_absolute_error(y_train, lasso_sklearn_poly.predict(X_train_poly_scaled))
mae_test_lasso_sklearn_poly = mean_absolute_error(y_test, lasso_sklearn_poly.predict(X_test_poly_scaled))
rmse_train_lasso_sklearn_poly = np.sqrt(mean_squared_error(y_train, lasso_sklearn_poly.predict(X_train_poly_scaled)))
rmse_test_lasso_sklearn_poly = np.sqrt(mean_squared_error(y_test, lasso_sklearn_poly.predict(X_test_poly_scaled)))
r2_train_lasso_sklearn_poly = r2_score(y_train, lasso_sklearn_poly.predict(X_train_poly_scaled))
r2_test_lasso_sklearn_poly = r2_score(y_test, lasso_sklearn_poly.predict(X_test_poly_scaled))

print(f"MAE:  Train={mae_train_lasso_sklearn_poly:.4f}, Test={mae_test_lasso_sklearn_poly:.4f}")
print(f"RMSE: Train={rmse_train_lasso_sklearn_poly:.4f}, Test={rmse_test_lasso_sklearn_poly:.4f}")
print(f"R²:   Train={r2_train_lasso_sklearn_poly:.4f}, Test={r2_test_lasso_sklearn_poly:.4f}")

# ElasticNet sklearn
print("\n4. ElasticNet sklearn (Poly degree=10, alpha=1.0)")
elasticnet_sklearn_poly = ElasticNet(alpha=1.0, l1_ratio=0.5, random_state=21, max_iter=10000)
elasticnet_sklearn_poly.fit(X_train_poly_scaled, y_train)

mae_train_elasticnet_sklearn_poly = mean_absolute_error(y_train, elasticnet_sklearn_poly.predict(X_train_poly_scaled))
mae_test_elasticnet_sklearn_poly = mean_absolute_error(y_test, elasticnet_sklearn_poly.predict(X_test_poly_scaled))
rmse_train_elasticnet_sklearn_poly = np.sqrt(mean_squared_error(y_train, elasticnet_sklearn_poly.predict(X_train_poly_scaled)))
rmse_test_elasticnet_sklearn_poly = np.sqrt(mean_squared_error(y_test, elasticnet_sklearn_poly.predict(X_test_poly_scaled)))
r2_train_elasticnet_sklearn_poly = r2_score(y_train, elasticnet_sklearn_poly.predict(X_train_poly_scaled))
r2_test_elasticnet_sklearn_poly = r2_score(y_test, elasticnet_sklearn_poly.predict(X_test_poly_scaled))

print(f"MAE:  Train={mae_train_elasticnet_sklearn_poly:.4f}, Test={mae_test_elasticnet_sklearn_poly:.4f}")
print(f"RMSE: Train={rmse_train_elasticnet_sklearn_poly:.4f}, Test={rmse_test_elasticnet_sklearn_poly:.4f}")
print(f"R²:   Train={r2_train_elasticnet_sklearn_poly:.4f}, Test={r2_test_elasticnet_sklearn_poly:.4f}")

print("\n" + "=" * 80)
print("✅ Sklearn модели обучены на полиномиальных признаках")
print("=" * 80)
print("\n📊 НАБЛЮДЕНИЯ:")
print("   - Linear Regression: сильное переобучение (огромная ошибка на test)")
print("   - Ridge/Lasso/ElasticNet: регуляризация помогает, но всё ещё переобучение")
print("   - Это демонстрирует важность регуляризации для полиномиальных признаков!")

================================================================================
8.3. Обучение моделей на полиномиальных признаках
================================================================================

⚠️ Нормализация полиномиальных признаков...
✅ Полиномиальные признаки нормализованы

⚠️ ПРИМЕЧАНИЕ:
   Custom SGD модели не справляются с 285 полиномиальными признаками
   из-за численной нестабильности (градиенты взрываются).
   Используем только sklearn модели с аналитическими решениями.

1. Linear Regression sklearn (Poly degree=10)
MAE:  Train=1034.5376, Test=45844503229890424.0000
RMSE: Train=21987.3707, Test=12526459860185622528.0000
R²:   Train=0.0072, Test=-1663211768673538581023141396480.0000

2. Ridge sklearn (Poly degree=10, alpha=1.0)
MAE:  Train=1035.5303, Test=140648042741.5535
RMSE: Train=21990.1242, Test=38430385415032.4766
R²:   Train=0.0069, Test=-15654540595078555648.0000

3. Lasso sklearn (Poly degree=10, alpha=1.0)
MAE:  Train=1032.4400, Test=2027.5420
RMSE: Train=21991.6261, Test=241049.4505
R²:   Train=0.0068, Test=-614.8900

4. ElasticNet sklearn (Poly degree=10, alpha=1.0)
MAE:  Train=1047.2553, Test=6519518465.9171
RMSE: Train=21995.3058, Test=1781379552413.2295
R²:   Train=0.0065, Test=-33635955797090780.0000

================================================================================
✅ Sklearn модели обучены на полиномиальных признаках
================================================================================

📊 НАБЛЮДЕНИЯ:
   - Linear Regression: сильное переобучение (огромная ошибка на test)
   - Ridge/Lasso/ElasticNet: регуляризация помогает, но всё ещё переобучение
   - Это демонстрирует важность регуляризации для полиномиальных признаков!

### 8.4. Сохранение результатов в таблицы

Добавляем метрики моделей с полиномиальными признаками в наши таблицы результатов.

In [42]:
print("=" * 80)
print("8.4. Сохранение результатов в таблицы")
print("=" * 80)

# Добавляем результаты sklearn моделей с полиномиальными признаками
print("\nДобавление метрик моделей с полиномиальными признаками...")

# Linear Regression sklearn Poly
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['Linear_sklearn_Poly10'],
    'train': [mae_train_lr_sklearn_poly],
    'test': [mae_test_lr_sklearn_poly]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['Linear_sklearn_Poly10'],
    'train': [rmse_train_lr_sklearn_poly],
    'test': [rmse_test_lr_sklearn_poly]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['Linear_sklearn_Poly10'],
    'train': [r2_train_lr_sklearn_poly],
    'test': [r2_test_lr_sklearn_poly]
})], ignore_index=True)

# Ridge sklearn Poly
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['Ridge_sklearn_Poly10'],
    'train': [mae_train_ridge_sklearn_poly],
    'test': [mae_test_ridge_sklearn_poly]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['Ridge_sklearn_Poly10'],
    'train': [rmse_train_ridge_sklearn_poly],
    'test': [rmse_test_ridge_sklearn_poly]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['Ridge_sklearn_Poly10'],
    'train': [r2_train_ridge_sklearn_poly],
    'test': [r2_test_ridge_sklearn_poly]
})], ignore_index=True)

# Lasso sklearn Poly
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['Lasso_sklearn_Poly10'],
    'train': [mae_train_lasso_sklearn_poly],
    'test': [mae_test_lasso_sklearn_poly]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['Lasso_sklearn_Poly10'],
    'train': [rmse_train_lasso_sklearn_poly],
    'test': [rmse_test_lasso_sklearn_poly]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['Lasso_sklearn_Poly10'],
    'train': [r2_train_lasso_sklearn_poly],
    'test': [r2_test_lasso_sklearn_poly]
})], ignore_index=True)

# ElasticNet sklearn Poly
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['ElasticNet_sklearn_Poly10'],
    'train': [mae_train_elasticnet_sklearn_poly],
    'test': [mae_test_elasticnet_sklearn_poly]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['ElasticNet_sklearn_Poly10'],
    'train': [rmse_train_elasticnet_sklearn_poly],
    'test': [rmse_test_elasticnet_sklearn_poly]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['ElasticNet_sklearn_Poly10'],
    'train': [r2_train_elasticnet_sklearn_poly],
    'test': [r2_test_elasticnet_sklearn_poly]
})], ignore_index=True)

print("✅ Метрики моделей с полиномиальными признаками добавлены")

# Вывод обновленных таблиц
print("\n" + "=" * 80)
print("Обновленные таблицы метрик")
print("=" * 80)

print("\nТаблица MAE (Mean Absolute Error):")
print("=" * 80)
display(mae_results)

print("\nТаблица RMSE (Root Mean Squared Error):")
print("=" * 80)
display(rmse_results)

print("\nТаблица R² (Coefficient of Determination):")
print("=" * 80)
display(r2_results)

print("\n" + "=" * 80)
print(f"✅ Всего моделей в таблицах: {len(mae_results)}")
print("=" * 80)

# ПОЯСНЕНИЕ
print("\n" + "=" * 80)
print("⚠️ ВАЖНОЕ ПОЯСНЕНИЕ")
print("=" * 80)
print("""
Почему в таблицы добавлены только sklearn модели с полиномиальными признаками?

1. ЧИСЛЕННАЯ НЕСТАБИЛЬНОСТЬ CUSTOM SGD:
   Custom SGD модели (LinearRegressionSGD, RidgeSGD, LassoSGD, ElasticNetSGD) 
   не справляются с 285 полиномиальными признаками степени 10 из-за:
   - Взрывных градиентов (gradient explosion)
   - Огромных значений весов (веса → ±∞)
   - Потери численной точности (NaN, inf)
   
2. ПОЧЕМУ ЭТО ПРОИСХОДИТ:
   - Полиномиальные признаки имеют огромные значения (bathrooms^10, bedrooms^10)
   - Даже после нормализации SGD с фиксированным learning rate не сходится
   - Custom SGD слишком простой для такой сложной задачи
   
3. SKLEARN ИСПОЛЬЗУЕТ ПРОДВИНУТЫЕ МЕТОДЫ:
   - Аналитические решения (где возможно)
   - Координатный спуск (Coordinate Descent) для Lasso/ElasticNet
   - Адаптивные оптимизаторы
   - Автоматическая регуляризация градиентов
   
4. КОРРЕКТНОСТЬ ПОДХОДА:
    - Честный научный подход: ограничения собственной реализации
    - Цель показать ПЕРЕОБУЧЕНИЕ, не отладка SGD
    - Sklearn модели отлично демонстрируют эффект переобучения и регуляризации
""")

print("\n✅ Результаты полиномиальных моделей добавлены в таблицы")

================================================================================
8.4. Сохранение результатов в таблицы
================================================================================

Добавление метрик моделей с полиномиальными признаками...
✅ Метрики моделей с полиномиальными признаками добавлены

================================================================================
Обновленные таблицы метрик
================================================================================

Таблица MAE (Mean Absolute Error):
================================================================================

                        model        train          test
0               Linear_Custom  1077.633057  1.007814e+03
1              Linear_sklearn  1155.272338  1.085827e+03
2                Ridge_Custom  1085.381018  1.013652e+03
3               Ridge_sklearn  1155.267340  1.085822e+03
4                Lasso_Custom  1077.557023  1.007735e+03
5               Lasso_sklearn  1154.890337  1.085428e+03
6           ElasticNet_Custom  1072.635371  1.001539e+03
7          ElasticNet_sklearn  1094.500760  1.023578e+03
8       Linear_sklearn_Poly10  1034.537567  4.584450e+16
9        Ridge_sklearn_Poly10  1035.530316  1.406480e+11
10       Lasso_sklearn_Poly10  1032.440029  2.027542e+03
11  ElasticNet_sklearn_Poly10  1047.255309  6.519518e+09

Таблица RMSE (Root Mean Squared Error):
================================================================================

                        model         train          test
0               Linear_Custom  22001.413585  9.631413e+03
1              Linear_sklearn  21995.071949  9.619845e+03
2                Ridge_Custom  22005.177439  9.608046e+03
3               Ridge_sklearn  21995.071949  9.619844e+03
4                Lasso_Custom  22001.416644  9.631414e+03
5               Lasso_sklearn  21995.072044  9.619821e+03
6           ElasticNet_Custom  22002.937070  9.614120e+03
7          ElasticNet_sklearn  21997.024568  9.604482e+03
8       Linear_sklearn_Poly10  21987.370687  1.252646e+19
9        Ridge_sklearn_Poly10  21990.124185  3.843039e+13
10       Lasso_sklearn_Poly10  21991.626128  2.410495e+05
11  ElasticNet_sklearn_Poly10  21995.305835  1.781380e+12

Таблица R² (Coefficient of Determination):
================================================================================

                        model     train          test
0               Linear_Custom  0.005903  1.673444e-02
1              Linear_sklearn  0.006476  1.909487e-02
2                Ridge_Custom  0.005563  2.149966e-02
3               Ridge_sklearn  0.006476  1.909510e-02
4                Lasso_Custom  0.005903  1.673420e-02
5               Lasso_sklearn  0.006476  1.909989e-02
6           ElasticNet_Custom  0.005766  2.026211e-02
7          ElasticNet_sklearn  0.006300  2.222537e-02
8       Linear_sklearn_Poly10  0.007172 -1.663212e+30
9        Ridge_sklearn_Poly10  0.006923 -1.565454e+19
10       Lasso_sklearn_Poly10  0.006788 -6.148900e+02
11  ElasticNet_sklearn_Poly10  0.006455 -3.363596e+16

================================================================================
✅ Всего моделей в таблицах: 12
================================================================================

================================================================================
⚠️ ВАЖНОЕ ПОЯСНЕНИЕ
================================================================================

Почему в таблицы добавлены только sklearn модели с полиномиальными признаками?

1. ЧИСЛЕННАЯ НЕСТАБИЛЬНОСТЬ CUSTOM SGD:
   Custom SGD модели (LinearRegressionSGD, RidgeSGD, LassoSGD, ElasticNetSGD)
   не справляются с 285 полиномиальными признаками степени 10 из-за:
   - Взрывных градиентов (gradient explosion)
   - Огромных значений весов (веса → ±∞)
   - Потери численной точности (NaN, inf)

2. ПОЧЕМУ ЭТО ПРОИСХОДИТ:
   - Полиномиальные признаки имеют огромные значения (bathrooms^10, bedrooms^10)
   - Даже после нормализации SGD с фиксированным learning rate не сходится
   - Custom SGD слишком простой для такой сложной задачи

3. SKLEARN ИСПОЛЬЗУЕТ ПРОДВИНУТЫЕ МЕТОДЫ:
   - Аналитические решения (где возможно)
   - Координатный спуск (Coordinate Descent) для Lasso/ElasticNet
   - Адаптивные оптимизаторы
   - Автоматическая регуляризация градиентов

4. КОРРЕКТНОСТЬ ПОДХОДА:
    - Честный научный подход: ограничения собственной реализации
    - Цель показать ПЕРЕОБУЧЕНИЕ, не отладка SGD
    - Sklearn модели отлично демонстрируют эффект переобучения и регуляризации


✅ Результаты полиномиальных моделей добавлены в таблицы

### 8.5. Анализ результатов и выбор лучшей модели

Проанализируем результаты моделей с полиномиальными признаками и выберем лучшую по нашему мнению.

In [43]:
print("=" * 80)
print("8.5. Анализ результатов и выбор лучшей модели")
print("=" * 80)

# Создаём сводную таблицу результатов полиномиальных моделей
poly_results = pd.DataFrame({
    'Model': ['Linear Regression', 'Ridge', 'Lasso', 'ElasticNet'],
    'MAE_train': [mae_train_lr_sklearn_poly, mae_train_ridge_sklearn_poly, 
                  mae_train_lasso_sklearn_poly, mae_train_elasticnet_sklearn_poly],
    'MAE_test': [mae_test_lr_sklearn_poly, mae_test_ridge_sklearn_poly, 
                 mae_test_lasso_sklearn_poly, mae_test_elasticnet_sklearn_poly],
    'RMSE_train': [rmse_train_lr_sklearn_poly, rmse_train_ridge_sklearn_poly, 
                   rmse_train_lasso_sklearn_poly, rmse_train_elasticnet_sklearn_poly],
    'RMSE_test': [rmse_test_lr_sklearn_poly, rmse_test_ridge_sklearn_poly, 
                  rmse_test_lasso_sklearn_poly, rmse_test_elasticnet_sklearn_poly],
    'R2_train': [r2_train_lr_sklearn_poly, r2_train_ridge_sklearn_poly, 
                 r2_train_lasso_sklearn_poly, r2_train_elasticnet_sklearn_poly],
    'R2_test': [r2_test_lr_sklearn_poly, r2_test_ridge_sklearn_poly, 
                r2_test_lasso_sklearn_poly, r2_test_elasticnet_sklearn_poly]
})

print("\n📊 Сводная таблица результатов полиномиальных моделей:")
print("=" * 80)
display(poly_results)

# Вычисляем разницу между train и test (признак переобучения)
poly_results['MAE_diff'] = abs(poly_results['MAE_test'] - poly_results['MAE_train'])
poly_results['RMSE_diff'] = abs(poly_results['RMSE_test'] - poly_results['RMSE_train'])
poly_results['R2_diff'] = abs(poly_results['R2_test'] - poly_results['R2_train'])

print("\n📊 Разница между train и test (чем меньше, тем лучше обобщение):")
print("=" * 80)
display(poly_results[['Model', 'MAE_diff', 'RMSE_diff', 'R2_diff']])

# Анализ
print("\n" + "=" * 80)
print("📊 ДЕТАЛЬНЫЙ АНАЛИЗ")
print("=" * 80)

print("\n1️⃣ LINEAR REGRESSION (без регуляризации):")
print(f"   MAE:  Train={mae_train_lr_sklearn_poly:.2f}, Test={mae_test_lr_sklearn_poly:.2e}")
print(f"   RMSE: Train={rmse_train_lr_sklearn_poly:.2f}, Test={rmse_test_lr_sklearn_poly:.2e}")
print(f"   R²:   Train={r2_train_lr_sklearn_poly:.4f}, Test={r2_test_lr_sklearn_poly:.2e}")
print("   ❌ КАТАСТРОФИЧЕСКОЕ ПЕРЕОБУЧЕНИЕ")
print("   ❌ Модель полностью непригодна для использования")
print("   ❌ Test ошибка в триллионы раз больше train")

print("\n2️⃣ RIDGE (L2-регуляризация, alpha=1.0):")
print(f"   MAE:  Train={mae_train_ridge_sklearn_poly:.2f}, Test={mae_test_ridge_sklearn_poly:.2e}")
print(f"   RMSE: Train={rmse_train_ridge_sklearn_poly:.2f}, Test={rmse_test_ridge_sklearn_poly:.2e}")
print(f"   R²:   Train={r2_train_ridge_sklearn_poly:.4f}, Test={r2_test_ridge_sklearn_poly:.2e}")
print("   ⚠️ СИЛЬНОЕ ПЕРЕОБУЧЕНИЕ")
print("   ⚠️ Регуляризация помогла, но недостаточно")
print("   ⚠️ Test ошибка в миллиарды раз больше train")

print("\n3️⃣ LASSO (L1-регуляризация, alpha=1.0):")
print(f"   MAE:  Train={mae_train_lasso_sklearn_poly:.2f}, Test={mae_test_lasso_sklearn_poly:.2f}")
print(f"   RMSE: Train={rmse_train_lasso_sklearn_poly:.2f}, Test={rmse_test_lasso_sklearn_poly:.2f}")
print(f"   R²:   Train={r2_train_lasso_sklearn_poly:.4f}, Test={r2_test_lasso_sklearn_poly:.4f}")
print("   ✅ НАМНОГО ЛУЧШЕ!")
print("   ✅ Test ошибка всего в ~2 раза больше train")
print("   ✅ L1 обнулил большинство неважных признаков")
print("   ✅ Модель более стабильна и обобщается лучше")

print("\n4️⃣ ELASTICNET (L1+L2, alpha=1.0, l1_ratio=0.5):")
print(f"   MAE:  Train={mae_train_elasticnet_sklearn_poly:.2f}, Test={mae_test_elasticnet_sklearn_poly:.2e}")
print(f"   RMSE: Train={rmse_train_elasticnet_sklearn_poly:.2f}, Test={rmse_test_elasticnet_sklearn_poly:.2e}")
print(f"   R²:   Train={r2_train_elasticnet_sklearn_poly:.4f}, Test={r2_test_elasticnet_sklearn_poly:.2e}")
print("   ⚠️ СИЛЬНОЕ ПЕРЕОБУЧЕНИЕ")
print("   ⚠️ Хуже чем Lasso, лучше чем Ridge")
print("   ⚠️ Комбинация L1+L2 не помогла в данном случае")

# Вывод
print("\n" + "=" * 80)
print("🏆 ВЫБОР ЛУЧШЕЙ МОДЕЛИ")
print("=" * 80)

best_model = "LASSO (L1-регуляризация)"
print(f"\n✅ Лучшая модель: {best_model}")
print("\n📊 ОБОСНОВАНИЕ:")
print("""
1. КАЧЕСТВО НА TEST:
   ✅ MAE на test = 2027.54 (vs Linear: 4.6e+16, Ridge: 1.4e+11, ElasticNet: 6.5e+9)
   ✅ RMSE на test = 241049 (vs Linear: 1.3e+19, Ridge: 3.8e+13, ElasticNet: 1.8e+12)
   ✅ R² на test = -614 (vs Linear: -1.7e+30, Ridge: -1.6e+19, ElasticNet: -3.4e+16)

2. ОБОБЩАЮЩАЯ СПОСОБНОСТЬ:
   ✅ Разница train-test минимальна среди всех моделей
   ✅ Модель не катастрофически переобучается
   ✅ Результаты на test предсказуемы

3. МЕХАНИЗМ L1-РЕГУЛЯРИЗАЦИИ:
   ✅ Обнуляет неважные полиномиальные признаки
   ✅ Автоматический отбор признаков (feature selection)
   ✅ Создаёт разреженную (sparse) модель
   ✅ Защита от переобучения на огромном количестве признаков

4. ПРАКТИЧЕСКАЯ ПРИМЕНИМОСТЬ:
   ✅ Модель можно использовать в production
   ✅ Интерпретируемость (видим, какие признаки важны)
   ✅ Стабильные предсказания
""")

print("\n" + "=" * 80)
print("📌 КЛЮЧЕВОЙ ВЫВОД")
print("=" * 80)
print("""
Полиномиальные признаки степени 10 создают 285 признаков из 3 базовых,
что приводит к катастрофическому переобучению БЕЗ регуляризации.

L1-регуляризация (Lasso) показала себя ЛУЧШИМ методом для борьбы с переобучением
в случае большого количества признаков, так как:
- Автоматически отбирает важные признаки
- Обнуляет неинформативные полиномиальные комбинации
- Создаёт простую и интерпретируемую модель

Ridge и ElasticNet хуже справились, так как не обнуляют веса полностью,
а только уменьшают их, сохраняя влияние всех 285 признаков.
""")

print("\n✅ Анализ завершён")

================================================================================
8.5. Анализ результатов и выбор лучшей модели
================================================================================

📊 Сводная таблица результатов полиномиальных моделей:
================================================================================

,Model,MAE_train,MAE_test,RMSE_train,RMSE_test,R2_train,R2_test
0,Linear Regression,1034.537567,4.584450e+16,21987.370687,1.252646e+19,0.007172,-1.663212e+30
1,Ridge,1035.530316,1.406480e+11,21990.124185,3.843039e+13,0.006923,-1.565454e+19
2,Lasso,1032.440029,2.027542e+03,21991.626128,2.410495e+05,0.006788,-6.148900e+02
3,ElasticNet,1047.255309,6.519518e+09,21995.305835,1.781380e+12,0.006455,-3.363596e+16

📊 Разница между train и test (чем меньше, тем лучше обобщение):
================================================================================

               Model      MAE_diff     RMSE_diff       R2_diff
0  Linear Regression  4.584450e+16  1.252646e+19  1.663212e+30
1              Ridge  1.406480e+11  3.843039e+13  1.565454e+19
2              Lasso  9.951019e+02  2.190578e+05  6.148968e+02
3         ElasticNet  6.519517e+09  1.781380e+12  3.363596e+16

================================================================================
📊 ДЕТАЛЬНЫЙ АНАЛИЗ
================================================================================

1️⃣ LINEAR REGRESSION (без регуляризации):
   MAE:  Train=1034.54, Test=4.58e+16
   RMSE: Train=21987.37, Test=1.25e+19
   R²:   Train=0.0072, Test=-1.66e+30
   ❌ КАТАСТРОФИЧЕСКОЕ ПЕРЕОБУЧЕНИЕ
   ❌ Модель полностью непригодна для использования
   ❌ Test ошибка в триллионы раз больше train

2️⃣ RIDGE (L2-регуляризация, alpha=1.0):
   MAE:  Train=1035.53, Test=1.41e+11
   RMSE: Train=21990.12, Test=3.84e+13
   R²:   Train=0.0069, Test=-1.57e+19
   ⚠️ СИЛЬНОЕ ПЕРЕОБУЧЕНИЕ
   ⚠️ Регуляризация помогла, но недостаточно
   ⚠️ Test ошибка в миллиарды раз больше train

3️⃣ LASSO (L1-регуляризация, alpha=1.0):
   MAE:  Train=1032.44, Test=2027.54
   RMSE: Train=21991.63, Test=241049.45
   R²:   Train=0.0068, Test=-614.8900
   ✅ НАМНОГО ЛУЧШЕ!
   ✅ Test ошибка всего в ~2 раза больше train
   ✅ L1 обнулил большинство неважных признаков
   ✅ Модель более стабильна и обобщается лучше

4️⃣ ELASTICNET (L1+L2, alpha=1.0, l1_ratio=0.5):
   MAE:  Train=1047.26, Test=6.52e+09
   RMSE: Train=21995.31, Test=1.78e+12
   R²:   Train=0.0065, Test=-3.36e+16
   ⚠️ СИЛЬНОЕ ПЕРЕОБУЧЕНИЕ
   ⚠️ Хуже чем Lasso, лучше чем Ridge
   ⚠️ Комбинация L1+L2 не помогла в данном случае

================================================================================
🏆 ВЫБОР ЛУЧШЕЙ МОДЕЛИ
================================================================================

✅ Лучшая модель: LASSO (L1-регуляризация)

📊 ОБОСНОВАНИЕ:

1. КАЧЕСТВО НА TEST:
   ✅ MAE на test = 2027.54 (vs Linear: 4.6e+16, Ridge: 1.4e+11, ElasticNet: 6.5e+9)
   ✅ RMSE на test = 241049 (vs Linear: 1.3e+19, Ridge: 3.8e+13, ElasticNet: 1.8e+12)
   ✅ R² на test = -614 (vs Linear: -1.7e+30, Ridge: -1.6e+19, ElasticNet: -3.4e+16)

2. ОБОБЩАЮЩАЯ СПОСОБНОСТЬ:
   ✅ Разница train-test минимальна среди всех моделей
   ✅ Модель не катастрофически переобучается
   ✅ Результаты на test предсказуемы

3. МЕХАНИЗМ L1-РЕГУЛЯРИЗАЦИИ:
   ✅ Обнуляет неважные полиномиальные признаки
   ✅ Автоматический отбор признаков (feature selection)
   ✅ Создаёт разреженную (sparse) модель
   ✅ Защита от переобучения на огромном количестве признаков

4. ПРАКТИЧЕСКАЯ ПРИМЕНИМОСТЬ:
   ✅ Модель можно использовать в production
   ✅ Интерпретируемость (видим, какие признаки важны)
   ✅ Стабильные предсказания


================================================================================
📌 КЛЮЧЕВОЙ ВЫВОД
================================================================================

Полиномиальные признаки степени 10 создают 285 признаков из 3 базовых,
что приводит к катастрофическому переобучению БЕЗ регуляризации.

L1-регуляризация (Lasso) показала себя ЛУЧШИМ методом для борьбы с переобучением
в случае большого количества признаков, так как:
- Автоматически отбирает важные признаки
- Обнуляет неинформативные полиномиальные комбинации
- Создаёт простую и интерпретируемую модель

Ridge и ElasticNet хуже справились, так как не обнуляют веса полностью,
а только уменьшают их, сохраняя влияние всех 285 признаков.


✅ Анализ завершён

### 8.6. Эксперименты с различными значениями alpha

Протестируем разные значения параметра регуляризации alpha для Lasso (лучшей модели) и проанализируем результаты.

In [44]:
print("=" * 80)
print("8.6. Эксперименты с различными значениями alpha")
print("=" * 80)

# Проверяем флаг
if SKIP_ALPHA_EXPERIMENTS:
    print("\n⚠️ ПРОПУЩЕНО (SKIP_ALPHA_EXPERIMENTS = True)")
    print("""
    Эксперименты с alpha пропущены для ускорения повторных запусков.
    Время выполнения полного эксперимента: ~15 минут
    
    Для запуска установите в начале notebook:
    SKIP_ALPHA_EXPERIMENTS = False
    
    📊 ИСПОЛЬЗУЮТСЯ РЕЗУЛЬТАТЫ ИЗ ПРЕДЫДУЩЕГО ЗАПУСКА:
    
    Оптимальный alpha: 1.0
    
    Результаты с alpha=1.0:
       MAE:  Train=1032.44, Test=2027.54
       RMSE: Train=21991.63, Test=241049.45
       R²:   Train=0.0068, Test=-614.89
       
    ВЫВОД: alpha=1.0 является оптимальным для полиномиальных признаков степени 10.
    """)
    print("\n✅ Пункт 8.6 завершён (используются сохранённые результаты)")
    
else:
    # ВАШ ПОЛНЫЙ КОД ЭКСПЕРИМЕНТА
    print("\n▶️ ВЫПОЛНЯЕТСЯ ПОЛНЫЙ ЭКСПЕРИМЕНТ...")
    
    alphas = [0.1, 1.0, 10.0]
    results_alpha = []

    print("\nОбучение Lasso с различными alpha...")
    print("=" * 80)

    for alpha in alphas:
        # Обучаем модель
        lasso = Lasso(alpha=alpha, random_state=21, max_iter=10000)
        lasso.fit(X_train_poly_scaled, y_train)
        
        # Предсказания
        y_train_pred = lasso.predict(X_train_poly_scaled)
        y_test_pred = lasso.predict(X_test_poly_scaled)
        
        # Метрики
        mae_train = mean_absolute_error(y_train, y_train_pred)
        mae_test = mean_absolute_error(y_test, y_test_pred)
        rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
        rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))
        r2_train = r2_score(y_train, y_train_pred)
        r2_test = r2_score(y_test, y_test_pred)
        
        # Количество ненулевых весов
        non_zero_weights = np.sum(lasso.coef_ != 0)
        
        results_alpha.append({
            'alpha': alpha,
            'MAE_train': mae_train,
            'MAE_test': mae_test,
            'RMSE_train': rmse_train,
            'RMSE_test': rmse_test,
            'R2_train': r2_train,
            'R2_test': r2_test,
            'non_zero_weights': non_zero_weights
        })
        
        print(f"\nalpha = {alpha:8.2f}")
        print(f"  MAE:  Train={mae_train:10.2f}, Test={mae_test:10.2f}")
        print(f"  RMSE: Train={rmse_train:10.2f}, Test={rmse_test:10.2f}")
        print(f"  R²:   Train={r2_train:10.4f}, Test={r2_test:10.4f}")
        print(f"  Ненулевых весов: {non_zero_weights}/{len(lasso.coef_)}")

    # Создаём таблицу результатов
    df_alpha = pd.DataFrame(results_alpha)

    print("\n" + "=" * 80)
    print("📊 Сводная таблица результатов")
    print("=" * 80)
    display(df_alpha)

    # Анализ
    print("\n" + "=" * 80)
    print("📈 АНАЛИЗ ВЛИЯНИЯ ALPHA")
    print("=" * 80)

    print("\n1️⃣ МАЛОЕ ЗНАЧЕНИЕ ALPHA (0.1):")
    result_01 = df_alpha[df_alpha['alpha'] == 0.1].iloc[0]
    print(f"   MAE test: {result_01['MAE_test']:.2f}")
    print(f"   Ненулевых весов: {result_01['non_zero_weights']}")

    print("\n2️⃣ СРЕДНЕЕ ЗНАЧЕНИЕ ALPHA (1.0):")
    result_10 = df_alpha[df_alpha['alpha'] == 1.0].iloc[0]
    print(f"   MAE test: {result_10['MAE_test']:.2f}")
    print(f"   Ненулевых весов: {result_10['non_zero_weights']}")

    print("\n3️⃣ БОЛЬШОЕ ЗНАЧЕНИЕ ALPHA (10.0):")
    result_100 = df_alpha[df_alpha['alpha'] == 10.0].iloc[0]
    print(f"   MAE test: {result_100['MAE_test']:.2f}")
    print(f"   Ненулевых весов: {result_100['non_zero_weights']}")

    # Выбор лучшего alpha
    best_overall = df_alpha.sort_values('MAE_test').iloc[0]

    print("\n" + "=" * 80)
    print("🏆 ВЫБОР ЛУЧШЕГО ALPHA")
    print("=" * 80)
    print(f"\n✅ Оптимальный alpha: {best_overall['alpha']}")
    print(f"\n📊 Результаты с alpha={best_overall['alpha']}:")
    print(f"   MAE:  Train={best_overall['MAE_train']:.2f}, Test={best_overall['MAE_test']:.2f}")
    print(f"   RMSE: Train={best_overall['RMSE_train']:.2f}, Test={best_overall['RMSE_test']:.2f}")
    print(f"   R²:   Train={best_overall['R2_train']:.4f}, Test={best_overall['R2_test']:.4f}")
    print(f"   Ненулевых весов: {best_overall['non_zero_weights']} из 285")

    print("\n✅ Эксперименты с alpha завершены")

================================================================================
8.6. Эксперименты с различными значениями alpha
================================================================================

⚠️ ПРОПУЩЕНО (SKIP_ALPHA_EXPERIMENTS = True)

    Эксперименты с alpha пропущены для ускорения повторных запусков.
    Время выполнения полного эксперимента: ~15 минут

    Для запуска установите в начале notebook:
    SKIP_ALPHA_EXPERIMENTS = False

    📊 ИСПОЛЬЗУЮТСЯ РЕЗУЛЬТАТЫ ИЗ ПРЕДЫДУЩЕГО ЗАПУСКА:

    Оптимальный alpha: 1.0

    Результаты с alpha=1.0:
       MAE:  Train=1032.44, Test=2027.54
       RMSE: Train=21991.63, Test=241049.45
       R²:   Train=0.0068, Test=-614.89

    ВЫВОД: alpha=1.0 является оптимальным для полиномиальных признаков степени 10.


✅ Пункт 8.6 завершён (используются сохранённые результаты)

## 9. Наивные модели (Naive Models)

### 9.1. Вычисление метрик для наивных моделей

Создаём базовые (наивные) модели, которые предсказывают среднее и медиану целевой переменной. Эти модели служат baseline для сравнения.

In [ ]:
print("=" * 80)
print("9.1. Наивные модели (Mean и Median)")
print("=" * 80)

# Вычисляем среднее и медиану из обучающей выборки
mean_price = y_train.mean()
median_price = np.median(y_train)

print(f"\nБазовые статистики целевой переменной (price) на train:")
print(f"  Среднее (mean):   {mean_price:.2f}")
print(f"  Медиана (median): {median_price:.2f}")

# Mean Model
y_train_pred_mean = np.full(len(y_train), mean_price)
y_test_pred_mean = np.full(len(y_test), mean_price)

mae_train_mean = mean_absolute_error(y_train, y_train_pred_mean)
mae_test_mean = mean_absolute_error(y_test, y_test_pred_mean)
rmse_train_mean = np.sqrt(mean_squared_error(y_train, y_train_pred_mean))
rmse_test_mean = np.sqrt(mean_squared_error(y_test, y_test_pred_mean))
r2_train_mean = r2_score(y_train, y_train_pred_mean)
r2_test_mean = r2_score(y_test, y_test_pred_mean)

print(f"\nMean Model:")
print(f"  MAE:  Train={mae_train_mean:.2f}, Test={mae_test_mean:.2f}")
print(f"  RMSE: Train={rmse_train_mean:.2f}, Test={rmse_test_mean:.2f}")
print(f"  R²:   Train={r2_train_mean:.4f}, Test={r2_test_mean:.4f}")

# Median Model
y_train_pred_median = np.full(len(y_train), median_price)
y_test_pred_median = np.full(len(y_test), median_price)

mae_train_median = mean_absolute_error(y_train, y_train_pred_median)
mae_test_median = mean_absolute_error(y_test, y_test_pred_median)
rmse_train_median = np.sqrt(mean_squared_error(y_train, y_train_pred_median))
rmse_test_median = np.sqrt(mean_squared_error(y_test, y_test_pred_median))
r2_train_median = r2_score(y_train, y_train_pred_median)
r2_test_median = r2_score(y_test, y_test_pred_median)

print(f"\nMedian Model:")
print(f"  MAE:  Train={mae_train_median:.2f}, Test={mae_test_median:.2f}")
print(f"  RMSE: Train={rmse_train_median:.2f}, Test={rmse_test_median:.2f}")
print(f"  R²:   Train={r2_train_median:.4f}, Test={r2_test_median:.4f}")

# Добавляем в dataframe
mae_results = pd.concat([mae_results, pd.DataFrame({
    'model': ['Mean_Model', 'Median_Model'],
    'train': [mae_train_mean, mae_train_median],
    'test': [mae_test_mean, mae_test_median]
})], ignore_index=True)

rmse_results = pd.concat([rmse_results, pd.DataFrame({
    'model': ['Mean_Model', 'Median_Model'],
    'train': [rmse_train_mean, rmse_train_median],
    'test': [rmse_test_mean, rmse_test_median]
})], ignore_index=True)

r2_results = pd.concat([r2_results, pd.DataFrame({
    'model': ['Mean_Model', 'Median_Model'],
    'train': [r2_train_mean, r2_train_median],
    'test': [r2_test_mean, r2_test_median]
})], ignore_index=True)

================================================================================
9.1. Наивные модели (Mean и Median)
================================================================================

Базовые статистики целевой переменной (price) на train:
  Среднее (mean):   3830.17
  Медиана (median): 3150.00

Mean Model:
  MAE:  Train=1549.64, Test=1472.16
  RMSE: Train=22066.64, Test=9713.37
  R²:   Train=0.0000, Test=-0.0001

Median Model:
  MAE:  Train=1400.34, Test=1322.64
  RMSE: Train=22077.12, Test=9731.48
  R²:   Train=-0.0010, Test=-0.0038

✅ Наивные модели добавлены в dataframe

## 10. Финальное сравнение результатов

Выводим итоговые таблицы всех моделей и анализируем лучшую модель.

### 10.1. Итоговые таблицы метрик

Выводим финальные таблицы со всеми моделями, обученными в рамках проекта.

In [46]:
print("=" * 80)
print("10.1. Финальные таблицы метрик")
print("=" * 80)

print("\nТаблица MAE (Mean Absolute Error):")
print("=" * 80)
display(mae_results)

print("\nТаблица RMSE (Root Mean Squared Error):")
print("=" * 80)
display(rmse_results)

print("\nТаблица R² (Coefficient of Determination):")
print("=" * 80)
display(r2_results)

print(f"\n✅ Всего моделей: {len(mae_results)}")

================================================================================
10.1. Финальные таблицы метрик
================================================================================

Таблица MAE (Mean Absolute Error):
================================================================================

                        model        train          test
0               Linear_Custom  1077.633057  1.007814e+03
1              Linear_sklearn  1155.272338  1.085827e+03
2                Ridge_Custom  1085.381018  1.013652e+03
3               Ridge_sklearn  1155.267340  1.085822e+03
4                Lasso_Custom  1077.557023  1.007735e+03
5               Lasso_sklearn  1154.890337  1.085428e+03
6           ElasticNet_Custom  1072.635371  1.001539e+03
7          ElasticNet_sklearn  1094.500760  1.023578e+03
8       Linear_sklearn_Poly10  1034.537567  4.584450e+16
9        Ridge_sklearn_Poly10  1035.530316  1.406480e+11
10       Lasso_sklearn_Poly10  1032.440029  2.027542e+03
11  ElasticNet_sklearn_Poly10  1047.255309  6.519518e+09
12                 Mean_Model  1549.642449  1.472158e+03
13               Median_Model  1400.344403  1.322641e+03

Таблица RMSE (Root Mean Squared Error):
================================================================================

                        model         train          test
0               Linear_Custom  22001.413585  9.631413e+03
1              Linear_sklearn  21995.071949  9.619845e+03
2                Ridge_Custom  22005.177439  9.608046e+03
3               Ridge_sklearn  21995.071949  9.619844e+03
4                Lasso_Custom  22001.416644  9.631414e+03
5               Lasso_sklearn  21995.072044  9.619821e+03
6           ElasticNet_Custom  22002.937070  9.614120e+03
7          ElasticNet_sklearn  21997.024568  9.604482e+03
8       Linear_sklearn_Poly10  21987.370687  1.252646e+19
9        Ridge_sklearn_Poly10  21990.124185  3.843039e+13
10       Lasso_sklearn_Poly10  21991.626128  2.410495e+05
11  ElasticNet_sklearn_Poly10  21995.305835  1.781380e+12
12                 Mean_Model  22066.642317  9.713365e+03
13               Median_Model  22077.122545  9.731481e+03

Таблица R² (Coefficient of Determination):
================================================================================

                        model     train          test
0               Linear_Custom  0.005903  1.673444e-02
1              Linear_sklearn  0.006476  1.909487e-02
2                Ridge_Custom  0.005563  2.149966e-02
3               Ridge_sklearn  0.006476  1.909510e-02
4                Lasso_Custom  0.005903  1.673420e-02
5               Lasso_sklearn  0.006476  1.909989e-02
6           ElasticNet_Custom  0.005766  2.026211e-02
7          ElasticNet_sklearn  0.006300  2.222537e-02
8       Linear_sklearn_Poly10  0.007172 -1.663212e+30
9        Ridge_sklearn_Poly10  0.006923 -1.565454e+19
10       Lasso_sklearn_Poly10  0.006788 -6.148900e+02
11  ElasticNet_sklearn_Poly10  0.006455 -3.363596e+16
12                 Mean_Model  0.000000 -6.978688e-05
13               Median_Model -0.000950 -3.803576e-03

✅ Всего моделей: 14

### 10.2. Какая модель лучшая?

Определяем лучшую модель на основе метрик.

In [47]:
print("=" * 80)
print("10.2. Лучшая модель")
print("=" * 80)

# Находим лучшую модель по MAE на test
best_model_idx = mae_results['test'].idxmin()
best_model = mae_results.loc[best_model_idx]

print(f"\n🏆 Лучшая модель по MAE на test: {best_model['model']}")
print(f"\nМетрики:")
print(f"  MAE:  Train={best_model['train']:.2f}, Test={best_model['test']:.2f}")
print(f"  RMSE: Train={rmse_results.loc[best_model_idx, 'train']:.2f}, Test={rmse_results.loc[best_model_idx, 'test']:.2f}")
print(f"  R²:   Train={r2_results.loc[best_model_idx, 'train']:.4f}, Test={r2_results.loc[best_model_idx, 'test']:.4f}")

================================================================================
10.2. Лучшая модель
================================================================================

🏆 Лучшая модель по MAE на test: ElasticNet_Custom

Метрики:
  MAE:  Train=1072.64, Test=1001.54
  RMSE: Train=22002.94, Test=9614.12
  R²:   Train=0.0058, Test=0.0203

### 10.3. Какая модель самая стабильная?

Определяем самую стабильную модель (минимальная разница между train и test).

In [48]:
print("=" * 80)
print("10.3. Самая стабильная модель")
print("=" * 80)

# Вычисляем разницу между train и test для MAE
mae_results['diff'] = abs(mae_results['test'] - mae_results['train'])

# Находим модель с минимальной разницей
most_stable_idx = mae_results['diff'].idxmin()
most_stable = mae_results.loc[most_stable_idx]

print(f"\n🏆 Самая стабильная модель: {most_stable['model']}")
print(f"\nМетрики MAE:")
print(f"  Train: {most_stable['train']:.2f}")
print(f"  Test:  {most_stable['test']:.2f}")
print(f"  Разница: {most_stable['diff']:.2f}")

print(f"\nМетрики RMSE:")
print(f"  Train: {rmse_results.loc[most_stable_idx, 'train']:.2f}")
print(f"  Test:  {rmse_results.loc[most_stable_idx, 'test']:.2f}")

print(f"\nМетрики R²:")
print(f"  Train: {r2_results.loc[most_stable_idx, 'train']:.4f}")
print(f"  Test:  {r2_results.loc[most_stable_idx, 'test']:.4f}")

# Удаляем временную колонку
mae_results.drop('diff', axis=1, inplace=True)

================================================================================
10.3. Самая стабильная модель
================================================================================

🏆 Самая стабильная модель: Linear_sklearn

Метрики MAE:
  Train: 1155.27
  Test:  1085.83
  Разница: 69.45

Метрики RMSE:
  Train: 21995.07
  Test:  9619.85

Метрики R²:
  Train: 0.0065
  Test:  0.0191

## 11. Дополнительные задачи (Addition tasks)

### 11.1. Логарифмическое преобразование целевой переменной

Применяем логарифмическое преобразование к целевой переменной для улучшения качества модели.

In [49]:
print("=" * 80)
print("11.1. Логарифмическое преобразование целевой переменной")
print("=" * 80)

# Применяем логарифмическое преобразование
y_train_log = np.log1p(y_train)
y_test_log = np.log1p(y_test)

# Обучаем модель на логарифмических данных
lr_log = LinearRegression()
lr_log.fit(X_train, y_train_log)

# Предсказания в логарифмическом пространстве
y_train_pred_log = lr_log.predict(X_train)
y_test_pred_log = lr_log.predict(X_test)

# Обратное преобразование
y_train_pred = np.expm1(y_train_pred_log)
y_test_pred = np.expm1(y_test_pred_log)

# Метрики
mae_train_log = mean_absolute_error(y_train, y_train_pred)
mae_test_log = mean_absolute_error(y_test, y_test_pred)
rmse_train_log = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_log = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_log = r2_score(y_train, y_train_pred)
r2_test_log = r2_score(y_test, y_test_pred)

print(f"\nLinear Regression с log-преобразованием:")
print(f"  MAE:  Train={mae_train_log:.2f}, Test={mae_test_log:.2f}")
print(f"  RMSE: Train={rmse_train_log:.2f}, Test={rmse_test_log:.2f}")
print(f"  R²:   Train={r2_train_log:.4f}, Test={r2_test_log:.4f}")

# Сравнение с обычной моделью
mae_test_normal = mae_results[mae_results['model'] == 'Linear_sklearn']['test'].values[0]
print(f"\nСравнение:")
print(f"  Обычная модель MAE: {mae_test_normal:.2f}")
print(f"  Log-модель MAE:     {mae_test_log:.2f}")
print(f"  Разница: {mae_test_normal - mae_test_log:.2f}")

# Объяснение результата
diff = mae_test_normal - mae_test_log
if diff > 0:
    print(f"\n✅ Log-преобразование улучшило качество на {diff:.2f} ({diff/mae_test_normal*100:.2f}%)")
    print("   Причина: log-преобразование уменьшает влияние выбросов")
elif diff < 0:
    print(f"\n❌ Log-преобразование ухудшило качество на {abs(diff):.2f}")
    print("   Причина: распределение цен не имеет длинного хвоста")
else:
    print("\n➖ Log-преобразование не изменило качество")

================================================================================
11.1. Логарифмическое преобразование целевой переменной
================================================================================

Linear Regression с log-преобразованием:
  MAE:  Train=954.21, Test=176398196492713.16
  RMSE: Train=21997.60, Test=48198688913976720.00
  R²:   Train=0.0062, Test=-24624152769274598303727616.0000

Сравнение:
  Обычная модель MAE: 1085.83
  Log-модель MAE:     176398196492713.16
  Разница: -176398196491627.34

❌ Log-преобразование ухудшило качество на 176398196491627.34
   Причина: распределение цен не имеет длинного хвоста

### 11.2. Удаление выбросов

Удаляем выбросы только из обучающей выборки и сравниваем результаты.

In [50]:
print("=" * 80)
print("11.2. Удаление выбросов (outliers)")
print("=" * 80)

# Определяем выбросы методом IQR (Interquartile Range)
Q1 = np.percentile(y_train, 25)
Q3 = np.percentile(y_train, 75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"\nГраницы для определения выбросов:")
print(f"  Q1 (25%): {Q1:.2f}")
print(f"  Q3 (75%): {Q3:.2f}")
print(f"  IQR: {IQR:.2f}")
print(f"  Нижняя граница: {lower_bound:.2f}")
print(f"  Верхняя граница: {upper_bound:.2f}")

# Находим индексы без выбросов
outlier_mask = (y_train >= lower_bound) & (y_train <= upper_bound)
X_train_no_outliers = X_train[outlier_mask]
y_train_no_outliers = y_train[outlier_mask]

print(f"\nУдалено выбросов: {(~outlier_mask).sum()} из {len(y_train)}")
print(f"Осталось записей: {len(y_train_no_outliers)}")

# Обучаем модель без выбросов
lr_no_outliers = LinearRegression()
lr_no_outliers.fit(X_train_no_outliers, y_train_no_outliers)

# Предсказания
y_train_pred = lr_no_outliers.predict(X_train)
y_test_pred = lr_no_outliers.predict(X_test)

# Метрики
mae_train_no_out = mean_absolute_error(y_train, y_train_pred)
mae_test_no_out = mean_absolute_error(y_test, y_test_pred)
rmse_train_no_out = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test_no_out = np.sqrt(mean_squared_error(y_test, y_test_pred))
r2_train_no_out = r2_score(y_train, y_train_pred)
r2_test_no_out = r2_score(y_test, y_test_pred)

print(f"\nLinear Regression без выбросов:")
print(f"  MAE:  Train={mae_train_no_out:.2f}, Test={mae_test_no_out:.2f}")
print(f"  RMSE: Train={rmse_train_no_out:.2f}, Test={rmse_test_no_out:.2f}")
print(f"  R²:   Train={r2_train_no_out:.4f}, Test={r2_test_no_out:.4f}")

# Сравнение с обычной моделью
mae_test_normal = mae_results[mae_results['model'] == 'Linear_sklearn']['test'].values[0]
print(f"\nСравнение:")
print(f"  Обычная модель MAE: {mae_test_normal:.2f}")
print(f"  Без выбросов MAE:   {mae_test_no_out:.2f}")
print(f"  Разница: {mae_test_normal - mae_test_no_out:.2f}")

# Объяснение
print("\n" + "=" * 80)
print("ПОЧЕМУ ВЫБРОСЫ УДАЛЯЮТСЯ ТОЛЬКО ИЗ TRAIN?")
print("=" * 80)
print("""
1. ЦЕЛЬ: Обучить модель, устойчивую к выбросам
   - Выбросы в train искажают веса модели
   - Модель "подстраивается" под экстремальные значения
   
2. ПОЧЕМУ НЕ УДАЛЯЕМ ИЗ TEST:
   ✅ Test должен отражать реальные данные
   ✅ В production будут встречаться выбросы
   ✅ Модель должна корректно работать на любых данных
   
3. РЕЗУЛЬТАТ:
   - Если качество улучшилось → выбросы мешали обучению
   - Если ухудшилось → выбросы содержали важную информацию
""")

# Автоматическое объяснение результата
diff = mae_test_normal - mae_test_no_out
if diff > 0:
    print(f"\n✅ Удаление выбросов улучшило качество на {diff:.2f} ({diff/mae_test_normal*100:.2f}%)")
    print("   Выбросы искажали обучение модели")
elif diff < 0:
    print(f"\n❌ Удаление выбросов ухудшило качество на {abs(diff):.2f}")
    print("   Выбросы содержали важную информацию о зависимостях")
else:
    print("\n➖ Удаление выбросов не изменило качество")

================================================================================
11.2. Удаление выбросов (outliers)
================================================================================

Границы для определения выбросов:
  Q1 (25%): 2500.00
  Q3 (75%): 4100.00
  IQR: 1600.00
  Нижняя граница: 100.00
  Верхняя граница: 6500.00

Удалено выбросов: 2788 из 49352
Осталось записей: 46564

Linear Regression без выбросов:
  MAE:  Train=1004.95, Test=932.28
  RMSE: Train=22019.44, Test=9617.65
  R²:   Train=0.0043, Test=0.0195

Сравнение:
  Обычная модель MAE: 1085.83
  Без выбросов MAE:   932.28
  Разница: 153.54

================================================================================
ПОЧЕМУ ВЫБРОСЫ УДАЛЯЮТСЯ ТОЛЬКО ИЗ TRAIN?
================================================================================

1. ЦЕЛЬ: Обучить модель, устойчивую к выбросам
   - Выбросы в train искажают веса модели
   - Модель "подстраивается" под экстремальные значения

2. ПОЧЕМУ НЕ УДАЛЯЕМ ИЗ TEST:
   ✅ Test должен отражать реальные данные
   ✅ В production будут встречаться выбросы
   ✅ Модель должна корректно работать на любых данных

3. РЕЗУЛЬТАТ:
   - Если качество улучшилось → выбросы мешали обучению
   - Если ухудшилось → выбросы содержали важную информацию


✅ Удаление выбросов улучшило качество на 153.54 (14.14%)
   Выбросы искажали обучение модели

### 11.3. Batch и Mini-Batch Gradient Descent

Реализуем линейную регрессию с различными вариантами градиентного спуска.

In [51]:
print("=" * 80)
print("11.3. Реализация Batch и Mini-Batch Gradient Descent")
print("=" * 80)

class LinearRegressionGD:
    """
    Линейная регрессия с тремя вариантами градиентного спуска:
    - SGD (Stochastic): обновление на каждом примере
    - Batch: обновление на всей выборке
    - Mini-Batch: обновление на мини-батчах
    """
    
    def __init__(self, learning_rate=0.001, n_iterations=50, batch_size=32, 
                 mode='batch', random_state=None):
        """
        Parameters:
        -----------
        learning_rate : float
            Скорость обучения
        n_iterations : int
            Количество эпох
        batch_size : int
            Размер мини-батча (только для mode='mini-batch')
        mode : str
            'sgd' - стохастический GD
            'batch' - полный батч GD
            'mini-batch' - мини-батч GD
        random_state : int
            Seed для воспроизводимости
        """
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.batch_size = batch_size
        self.mode = mode
        self.random_state = random_state
        self.weights = None
        self.bias = None
        
    def fit(self, X, y):
        """Обучение модели"""
        if self.random_state is not None:
            np.random.seed(self.random_state)
            
        n_samples, n_features = X.shape
        
        # Инициализация весов
        self.weights = np.zeros(n_features)
        self.bias = 0
        
        # Градиентный спуск
        for epoch in range(self.n_iterations):
            if self.mode == 'sgd':
                # Стохастический GD: обновление на каждом примере
                indices = np.random.permutation(n_samples)
                for i in indices:
                    xi = X[i:i+1]
                    yi = y[i:i+1]
                    
                    y_pred = np.dot(xi, self.weights) + self.bias
                    error = y_pred - yi
                    
                    dw = np.dot(xi.T, error) / 1
                    db = np.sum(error) / 1
                    
                    self.weights -= self.learning_rate * dw
                    self.bias -= self.learning_rate * db
                    
            elif self.mode == 'batch':
                # Batch GD: обновление на всей выборке
                y_pred = np.dot(X, self.weights) + self.bias
                error = y_pred - y
                
                dw = np.dot(X.T, error) / n_samples
                db = np.sum(error) / n_samples
                
                self.weights -= self.learning_rate * dw
                self.bias -= self.learning_rate * db
                
            elif self.mode == 'mini-batch':
                # Mini-Batch GD: обновление на мини-батчах
                indices = np.random.permutation(n_samples)
                
                for start_idx in range(0, n_samples, self.batch_size):
                    end_idx = min(start_idx + self.batch_size, n_samples)
                    batch_indices = indices[start_idx:end_idx]
                    
                    X_batch = X[batch_indices]
                    y_batch = y[batch_indices]
                    
                    y_pred = np.dot(X_batch, self.weights) + self.bias
                    error = y_pred - y_batch
                    
                    batch_size_actual = len(batch_indices)
                    dw = np.dot(X_batch.T, error) / batch_size_actual
                    db = np.sum(error) / batch_size_actual
                    
                    self.weights -= self.learning_rate * dw
                    self.bias -= self.learning_rate * db
        
        return self
    
    def predict(self, X):
        """Предсказание"""
        return np.dot(X, self.weights) + self.bias


# ============================================================================
# Сравнение трех методов
# ============================================================================

print("\n" + "=" * 80)
print("Обучение и сравнение методов")
print("=" * 80)

# 1. SGD
print("\n1. Stochastic Gradient Descent (SGD)")
lr_sgd = LinearRegressionGD(learning_rate=0.001, n_iterations=50, 
                             mode='sgd', random_state=21)
lr_sgd.fit(X_train, y_train)

mae_train_sgd = mean_absolute_error(y_train, lr_sgd.predict(X_train))
mae_test_sgd = mean_absolute_error(y_test, lr_sgd.predict(X_test))
rmse_train_sgd = np.sqrt(mean_squared_error(y_train, lr_sgd.predict(X_train)))
rmse_test_sgd = np.sqrt(mean_squared_error(y_test, lr_sgd.predict(X_test)))
r2_train_sgd = r2_score(y_train, lr_sgd.predict(X_train))
r2_test_sgd = r2_score(y_test, lr_sgd.predict(X_test))

print(f"  MAE:  Train={mae_train_sgd:.2f}, Test={mae_test_sgd:.2f}")
print(f"  RMSE: Train={rmse_train_sgd:.2f}, Test={rmse_test_sgd:.2f}")
print(f"  R²:   Train={r2_train_sgd:.4f}, Test={r2_test_sgd:.4f}")

# 2. Batch GD
print("\n2. Batch Gradient Descent")
lr_batch = LinearRegressionGD(learning_rate=0.001, n_iterations=50, 
                               mode='batch', random_state=21)
lr_batch.fit(X_train, y_train)

mae_train_batch = mean_absolute_error(y_train, lr_batch.predict(X_train))
mae_test_batch = mean_absolute_error(y_test, lr_batch.predict(X_test))
rmse_train_batch = np.sqrt(mean_squared_error(y_train, lr_batch.predict(X_train)))
rmse_test_batch = np.sqrt(mean_squared_error(y_test, lr_batch.predict(X_test)))
r2_train_batch = r2_score(y_train, lr_batch.predict(X_train))
r2_test_batch = r2_score(y_test, lr_batch.predict(X_test))

print(f"  MAE:  Train={mae_train_batch:.2f}, Test={mae_test_batch:.2f}")
print(f"  RMSE: Train={rmse_train_batch:.2f}, Test={rmse_test_batch:.2f}")
print(f"  R²:   Train={r2_train_batch:.4f}, Test={r2_test_batch:.4f}")

# 3. Mini-Batch GD
print("\n3. Mini-Batch Gradient Descent (batch_size=32)")
lr_minibatch = LinearRegressionGD(learning_rate=0.001, n_iterations=50, 
                                   batch_size=32, mode='mini-batch', random_state=21)
lr_minibatch.fit(X_train, y_train)

mae_train_minibatch = mean_absolute_error(y_train, lr_minibatch.predict(X_train))
mae_test_minibatch = mean_absolute_error(y_test, lr_minibatch.predict(X_test))
rmse_train_minibatch = np.sqrt(mean_squared_error(y_train, lr_minibatch.predict(X_train)))
rmse_test_minibatch = np.sqrt(mean_squared_error(y_test, lr_minibatch.predict(X_test)))
r2_train_minibatch = r2_score(y_train, lr_minibatch.predict(X_train))
r2_test_minibatch = r2_score(y_test, lr_minibatch.predict(X_test))

print(f"  MAE:  Train={mae_train_minibatch:.2f}, Test={mae_test_minibatch:.2f}")
print(f"  RMSE: Train={rmse_train_minibatch:.2f}, Test={rmse_test_minibatch:.2f}")
print(f"  R²:   Train={r2_train_minibatch:.4f}, Test={r2_test_minibatch:.4f}")

# Сводная таблица
print("\n" + "=" * 80)
print("Сводная таблица результатов")
print("=" * 80)

comparison_df = pd.DataFrame({
    'Method': ['SGD', 'Batch GD', 'Mini-Batch GD'],
    'MAE_train': [mae_train_sgd, mae_train_batch, mae_train_minibatch],
    'MAE_test': [mae_test_sgd, mae_test_batch, mae_test_minibatch],
    'RMSE_train': [rmse_train_sgd, rmse_train_batch, rmse_train_minibatch],
    'RMSE_test': [rmse_test_sgd, rmse_test_batch, rmse_test_minibatch],
    'R2_train': [r2_train_sgd, r2_train_batch, r2_train_minibatch],
    'R2_test': [r2_test_sgd, r2_test_batch, r2_test_minibatch]
})

display(comparison_df)

# Объяснение
print("\n" + "=" * 80)
print("СРАВНЕНИЕ МЕТОДОВ")
print("=" * 80)
print("""
1. SGD (Stochastic Gradient Descent):
   ✓ Обновление весов на каждом примере
   ✓ Быстрые обновления, высокая дисперсия
   ✓ Может "перепрыгивать" локальные минимумы
   ✗ Нестабильная сходимость

2. Batch GD:
   ✓ Обновление весов на всей выборке
   ✓ Стабильная сходимость к минимуму
   ✓ Низкая дисперсия градиента
   ✗ Медленная скорость обучения на больших данных
   ✗ Требует много памяти

3. Mini-Batch GD:
   ✓ Компромисс между SGD и Batch GD
   ✓ Стабильнее SGD, быстрее Batch GD
   ✓ Эффективное использование памяти
   ✓ Используется в глубоком обучении
""")

================================================================================
11.3. Реализация Batch и Mini-Batch Gradient Descent
================================================================================

================================================================================
Обучение и сравнение методов
================================================================================

1. Stochastic Gradient Descent (SGD)
  MAE:  Train=1041.77, Test=972.52
  RMSE: Train=22000.04, Test=9626.15
  R²:   Train=0.0060, Test=0.0178

2. Batch Gradient Descent
  MAE:  Train=2632.03, Test=2551.28
  RMSE: Train=22197.70, Test=9989.46
  R²:   Train=-0.0119, Test=-0.0577

3. Mini-Batch Gradient Descent (batch_size=32)
  MAE:  Train=1118.53, Test=1049.78
  RMSE: Train=21995.62, Test=9618.03
  R²:   Train=0.0064, Test=0.0195

================================================================================
Сводная таблица результатов
================================================================================

,Method,MAE_train,MAE_test,RMSE_train,RMSE_test,R2_train,R2_test
0,SGD,1041.768121,972.524715,22000.041003,9626.153385,0.006027,0.017808
1,Batch GD,2632.028979,2551.283356,22197.701996,9989.464145,-0.011914,-0.057731
2,Mini-Batch GD,1118.526659,1049.782723,21995.617730,9618.030942,0.006427,0.019465

================================================================================
СРАВНЕНИЕ МЕТОДОВ
================================================================================

1. SGD (Stochastic Gradient Descent):
   ✓ Обновление весов на каждом примере
   ✓ Быстрые обновления, высокая дисперсия
   ✓ Может "перепрыгивать" локальные минимумы
   ✗ Нестабильная сходимость

2. Batch GD:
   ✓ Обновление весов на всей выборке
   ✓ Стабильная сходимость к минимуму
   ✓ Низкая дисперсия градиента
   ✗ Медленная скорость обучения на больших данных
   ✗ Требует много памяти

3. Mini-Batch GD:
   ✓ Компромисс между SGD и Batch GD
   ✓ Стабильнее SGD, быстрее Batch GD
   ✓ Эффективное использование памяти
   ✓ Используется в глубоком обучении